### ISSUE TITLE
Some tests fail in os windows

### ISSUE THREAD

**Issue by EstebanJesus** [gavv/httpexpect#103]
When cloning the project on a windows OS and running the tests I get some failures, it is related to the creation of temporary files.

**Comment by EstebanJesus** [comment]
Great, with the version you created it works perfect for me.

**Comment by clobrano** [comment]
@gavv, what am I supposed to do with this?

**Comment by gavv** [comment]
@clobrano the fix is merged. Does this problem still reproduce for you on fresh master?

**Comment by clobrano** [comment]
unfortunately I cannot re-test this anymore
