### ISSUE TITLE
Set multiple status as success criteria

### ISSUE THREAD

**Issue by ihassanyousaf** [gavv/httpexpect#109]
Hi, 

Is there anyway to set multiple statuses as success criteria. 
e-g 200 and 404 as success criteria? 

The usecase is like deleting something from API let's just say a project,  api will return 2xx in case the project existed and deleted and 404 in case the project didn't exist. 

both case are considered as success as the main idea is not to have a project in the system. 

Is there anyway of doing this? If not, do you think it might be a good idea of implementing this?

**Comment by ahdekkers** [comment]
I'd be happy to work on this if help is desired

**Comment by gavv** [comment]
Hi, sure, this is a valid feature, pull requests are welcome.

We already have methods `Status` and `StatusRange`, we could add a new method `StatusList` that accepts a list of statuses as variadic argument.

**Comment by edwinwijaya94** [comment]
Hi @gavv @ahdekkers I'll be happy to help if this issue still open

**Comment by gavv** [comment]
@edwinwijaya94 Great, you're welcome, thank you.

**Comment by gavv** [comment]
@ihassanyousaf this feature is merged to master now
