### ISSUE TITLE
I have issue when testing subdomains

### ISSUE THREAD

**Issue by kataras** [gavv/httpexpect#13]
Hello my friend, I have some issues when testing subdomains, the same time the browser returns status 200 ( with cleaned cache) the httpexpect returns 404, here is example code:

```go

const (
	scheme = "http://"
	domain = "mydomain.com"
	port   = 8080 // this will go as test flag some day.
)

var (
	addr = domain + ":" + strconv.Itoa(port)
	host = scheme + addr
)

// tester_lister starts the server to listen on, this is useful ONLY WHEN TEST (AND) SUBDOMAINS,
// the hosts file (on windows) must be setted as '127.0.0.1 mydomain.com' & '127.0.0.1 mysubdomain.mydomain.com'
func tester_listen(api *iris.Framework, t *testing.T) *httpexpect.Expect {
	api.Config.DisableBanner = true
	go api.Listen(addr)
	time.Sleep(time.Duration(10) * time.Second)
	return httpexpect.WithConfig(httpexpect.Config{
		BaseURL: host,
		Client: &http.Client{
			Transport: httpexpect.NewFastBinder(api.HTTPServer.Handler),
			Jar:       httpexpect.NewJar(),
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
			httpexpect.NewDebugPrinter(t, true),
		},
	})
}


// and the test:
      	api := iris.New()
//...
	mysubdomain := api.Party("mysubdomain.").Get("/get", func(ctx *iris.Context) {
		writeValues(ctx)
	})
	h := tester_listen(api, t)
//...
        	h.Request("GET", scheme+"mysubdomain."+addr+"/get").Expect().Status(iris.StatusOK).JSON().Object().Equal(values)
	//...

```

As you see I put a real server running & time.Sleep of 10 seconds in order to have time to test it on my browser, there the subdomain worked, at the tests it shows me:

```sh
printer.go:55: GET http://mysubdomain.mydomain.com:8080/get HTTP/1.1
                Host: mydomain.com:8080

        printer.go:72: HTTP/0.0 404 Not Found 0
                Content-Type: text/plain; charset=utf-8

                Not Found
        Error Trace:    reporter.go:22
                        chain.go:21
                        response.go:437
                        response.go:123
                        sessions_test.go:63
        Error:
                        expected status equal to:
                         "200 OK"

                        but got:
                         "404 Not Found"

```

Complete code:

```go
// file ./test/iris_test.go
//Package test -v ./... builds all tests
package test

import (
	"net/http"
	"strconv"
	"testing"

	"github.com/gavv/httpexpect"
	"github.com/kataras/iris"
)

const (
	scheme = "http://"
	domain = "mydomain.com"
	port   = 8080 // this will go as test flag some day.

	// will start  the server to real listen , this is useful ONLY WHEN TEST (AND) SUBDOMAINS,
	// the hosts file (on windows) must be setted as '127.0.0.1 mydomain.com' & '127.0.0.1 mysubdomain.mydomain.com'
	enable_subdomains_tests = true // this will go as test flag some day also.
	subdomain               = "mysubdomain"
)

var (
	addr           = domain + ":" + strconv.Itoa(port)
	host           = scheme + addr
	subdomain_host = scheme + subdomain + "." + addr
)

func tester(api *iris.Framework, t *testing.T) *httpexpect.Expect {
	api.Config.DisableBanner = true
	go func() { // no need goroutine here, we could just add go api.Listen(addr) but newcomers can see easier that these will run in a non-blocking way
		if enable_subdomains_tests {
			api.Listen(addr)
		} else {
			api.NoListen(addr)
		}
	}()

	if ok := <-api.Available; !ok {
		panic("Unexpected error: server cannot start, please report this as bug!!")
	}
	close(api.Available)

	handler := api.HTTPServer.Handler
	return httpexpect.WithConfig(httpexpect.Config{
		BaseURL: host,
		Client: &http.Client{
			Transport: httpexpect.NewFastBinder(handler),
			Jar:       httpexpect.NewJar(),
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
			httpexpect.NewDebugPrinter(t, true),
		},
	})

}

```
```go
//file ./test/sessions_test.go

//Package test -v ./... builds all tests
package test

import (
	"testing"

	"github.com/kataras/iris"
)

func TestSessions(t *testing.T) {
	sessionId := "mycustomsessionid"

	values := map[string]interface{}{
		"Name":   "iris",
		"Months": "4",
		"Secret": "dsads£2132215£%%Ssdsa",
	}

	api := iris.New()

	api.Config.Sessions.Cookie = sessionId
	writeValues := func(ctx *iris.Context) {
		sessValues := ctx.Session().GetAll()
		ctx.JSON(iris.StatusOK, sessValues)
	}

	api.Post("set", func(ctx *iris.Context) {
		vals := make(map[string]interface{}, 0)
		if err := ctx.ReadJSON(&vals); err != nil {
			t.Fatalf("Cannot readjson. Trace %s", err.Error())
		}
		for k, v := range vals {
			ctx.Session().Set(k, v)
		}
	})

	api.Get("/get", func(ctx *iris.Context) {
		writeValues(ctx)
	})

	if enable_subdomains_tests {
		api.Party(subdomain+".").Get("/get", func(ctx *iris.Context) {
			writeValues(ctx)
		})
	}

	api.Get("/clear", func(ctx *iris.Context) {
		ctx.Session().Clear()
		writeValues(ctx)
	})

	api.Get("/destroy", func(ctx *iris.Context) {
		ctx.SessionDestroy()
		writeValues(ctx)
		// the cookie and all values should be empty
	})

	h := tester(api, t)

	h.POST("/set").WithJSON(values).Expect().Status(iris.StatusOK).Cookies().NotEmpty()
	h.GET("/get").Expect().Status(iris.StatusOK).JSON().Object().Equal(values)
	if enable_subdomains_tests {
		h.Request("GET", subdomain_host+"/get").Expect().Status(iris.StatusOK).JSON().Object().Equal(values)
	}

	// test destory which also clears first
	d := h.GET("/destroy").Expect().Status(iris.StatusOK)
	d.JSON().Object().Empty()
	d.Cookies().ContainsOnly(sessionId)
	// set and clear again
	h.POST("/set").WithJSON(values).Expect().Status(iris.StatusOK).Cookies().NotEmpty()
	h.GET("/clear").Expect().Status(iris.StatusOK).JSON().Object().Empty()

}
```

When ` enable_subdomains_tests` is false the tests are passed*

---------

Thoughts: If I remove the BaseURL entirely I have two problems:
-  the ` h.GET(host + "/get").Expect().Status(iris.StatusOK).JSON().Object().Equal(values)`  returns ` empty json response` , while it's not empty. **Solution**:  if you check manually the domain field of a cookie header, keep note of the [RFC2109](https://www.ietf.org/rfc/rfc2109.txt), **meaning that a domain field can be filled as `.mydomain.com` that's means that the mydomain.com AND all first-level subdomains have access to this cookie** , iris sets the domain field to "."+domain in order to achieve the  sessions persistence  on subdomains, which is working well on all browsers)

- I have to put the http://mydomain.com in frontof  all the .GET/POST... and it is not a good idea, I think the BaseURL takes the host and all requests are declared as relative to it. **Solution**: you could check if the 'path' starts with http://, https://, ws:// then it is url and not a BaseURL's relative path.  

If you want to run the code by yourself or add some httpexpect fixes so I can learn from those, do that in [iris-contrib/tests](https://github.com/iris-contrib/tests) ( I updated the tests), thanks!!

**Comment by gavv** [comment]
Thanks for reporting, I'll look at it.

BTW, are you using `api.Listen()` and `httpexpect.NewFastBinder()` at the same time? It's strange, because when you use default (nil) `Transport` for `http.Client`, it connects to server via http, so you need `Listen()`. But if you use `FastBinder`, it calls handler directly, so you don't need `Listen()`.

**Comment by kataras** [comment]
Yes I though that too, but it gives 404 again :/

**Comment by gavv** [comment]
What about `.XML()`, it requires some research. I'm not very familiar with XML, but I guess current assertions (value, object, array, string, number, boolean) are not enough.

**Comment by gavv** [comment]
Another note: currently `Request()`, `GET()`, `POST()`, etc. assume that user passed *unescaped path*, not an url (which is escaped by definition). This path is stored into `http.Request.URL.Path`, and so is escaped when `url.String()` is called.

So strictly speaking it's incorrect to use `GET(host+path)` with current API. We probably want a better API for subdomain support.

**Comment by kataras** [comment]
Yes I had this issue before, take a look at the iris code base for both questions (xml  on context and how I handle subdomains on http.go->muxServe->ServeRequest)

**Comment by gavv** [comment]
@kataras 

1. We now have `Request.WithURL()`.

    While `e.GET()`, `e.POST()`, etc. accept *path*, `WithURL` may be used to overwrite `BaseURL` to single request. Path is appended to this URL.

2. We now have [reusable request builders](https://github.com/gavv/httpexpect/#reusable-builders).

    You can do the following to avoid writing `WithURL` for every request:

    ```go
	sub := e.Builder(func(req *httpexpect.Request) {
		req.WithURL("http://subdomain.domain.com")
	})

	sub.POST("/path").
		Expect().
		Status(http.StatusOK)
    ```

3. [Iris example](https://github.com/gavv/httpexpect/blob/master/example/iris_test.go#L144) is updated.

    It now includes cookies + subdomains test. Works for me.

4. I've also updated `iris-contrib/tests` in my fork.

    See [this commit](https://github.com/gavv/iris-tests/commit/1cfc44829656e0a07acf7abfce5d8928ead2273f). Works for me.

**Comment by kataras** [comment]
That's excellent nice, I can continue testing now!!  thanks for updating iris example also, and about the commit, you have to make a pull request in order to be combined with iris-contrib/tests

**Comment by gavv** [comment]
> you have to make a pull request in order to be combined with iris-contrib/tests

OK.

**Comment by kataras** [comment]
Just to verify, the subdomain with builder works perfect!

**Comment by gavv** [comment]
Good.
