### ISSUE TITLE
Implement String.HasPrefix and String.HasSuffix

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#153]
Implement new `String` assertions:

* `String.HasPrefix` - succeeds if string has given prefix
* `String.HasSuffix` - succeeds if string has given suffix
* `String.HasPrefixFold` - succeeds if string has given prefix, case insensitive
* `String.HasSuffixFold` - succeeds if string has given suffix, case insensitive

For every assertion, also add negative version (`NotHasPrefix`, `NotHasSuffix`, etc).

Each assertion should have documentation comment with example and be covered by unit tests.

See also #154.

**Comment by edwinwijaya94** [comment]
Hi @gavv I would like to work on this issue

**Comment by gavv** [comment]
You're welcome, thanks

**Comment by gavv** [comment]
Merged.
