### ISSUE TITLE
Implement Array.ContainsAny

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#157]
We already have `Array.Contains` and `Array.ContainsOnly`.

It would be handy to have `ContainsAny`, which succeeds if array contains any of the specified elements.

We also need the counterpart `NotContainsAny`.

Assertions should have documentation comment with example and be covered by unit tests.

**Comment by ni3k** [comment]
Hi @gavv can I work on this issue? I think I could come up with a PR today

**Comment by gavv** [comment]
@ni3k Great, you're welcome, thanks!

**Comment by gavv** [comment]
Landed.
