### ISSUE TITLE
Implement Array.IsOrdered

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#158]
Implement new assertion `Array.IsOrdered`, which succeeds if array elements are sorted. Also add counterpart `NotIsOrdered`.

It should have optional argument `less func(index int, value *Value)`, which defines the function to compare elements (like in sort.Slice):

* If function is provided, `IsOrdered` can compare arbitrary arrays.

* If function is not provided, `IsOrdered` should use builtin comparison for booleans, numbers, strings, durations, and datetimes. It will require that all array elements be of the same type and it is one of these types (after converting to canonical form, see canon.go).

See `String.AsNumber` for en example of optional argument.

Assertions should have documentation comment with example and be covered by unit tests.

**Comment by edwinwijaya94** [comment]
Hi @gavv I can help on this

**Comment by gavv** [comment]
Thanks!
