### ISSUE TITLE
Add DefaultFormatter.EnableStacktrace

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#160]
Add flag `EnableStacktrace` to `DefaultFormatter` that enables printing of stacktrace on failure. Formatted stacktrace should be added to `FormatData` (likely as slice of strings) and used in failure template.

See also #159.

**Comment by fahimbagar** [comment]
Hi @gavv, just checking.

What's the difference between this and the chain path? and what's the expected result here? :raised_back_of_hand: 

Sorry for the dumb question :smile:

**Comment by gavv** [comment]
Hi, this issue is about regular go stacktrace / backtrace, like you see on panic or crash

https://dev.to/mcaci/reading-stack-traces-in-go-3ah5

It is possible to retrieve it programmatically

**Comment by gavv** [comment]
Chain path, on the other hand, is a logical representation of path in httpexpect object tree

It doesn't include actual function frames, though it provides similar information in some sense

Most notably, chain path doesn't tell anything about location in user code. It shows path to object, but it doesn't show where that object were actually used when failure happened (maybe it was stored to variable and used later)

**Comment by fahimbagar** [comment]
Understood. I'll learn about go stacktrace / backtrace first and message you here afterward unless someone picks this up.
Thanks for the answer @gavv.

**Comment by diPhantxm** [comment]
Hi @gavv
I'm interested in this issue. May I take it?

**Comment by gavv** [comment]
Landed
