### ISSUE TITLE
Support colored output

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#161]
Modify DefaultFormatter to support colorized output.

It should provide three color modes, controlled by an option:

* auto (used by default) - enable colors if testing.Verbose() is true and stdout is a tty / console
* always - always use colors
* never - never use colors

Color support should work for both unix and windows.

Colors should be injected into failure template using template functions, but should not be present in FormatData. This way users that use DefaultFormatter with custom templates won't be affected.

**Comment by gavv** [comment]
Maybe we can also use this https://github.com/TylerBrock/colorjson

**Comment by dhanusaputra** [comment]
hi gavv is it ok for me to do this? thanks

**Comment by gavv** [comment]
You're welcome!

**Comment by gavv** [comment]
Two follow-up issues: #334, #335.
