### ISSUE TITLE
Improve usage checks in Request and Websocket

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#162]
`Request` and `Websocket` have the following workflow:

* create instance
* likely, call `WithXXX()` methods multiple times
* call `Expect()` method

It is not allowed to call `WithXXX()` after `Expect()` is called. It is also not allowed to call `Expect()` more than once. However, these requirements are not documented and checked.

What we should do:

* Document these requirements in comment for `Expect`.
* Report failure if these requirements are violated with `Type` set to `AssertUsage` and an explanatory message.
* Add unit tests that cover these failure reports.

**Comment by gavv** [comment]
Hi,

I mean the follwoing misuses:

```
req := e.GET("/test")

req.WithXXX(...) // ok
req.WithXXX(...) // ok
req.Expect() // ok

req.WithXXX() // bad, With not allowed after Expect; should report failure
req.Expect() // bad, multiple Expect calls not allowed; should report failure
```

**Comment by gavv** [comment]
Let me know if you would like to be assigned.

**Comment by chunweii** [comment]
Yes please, thanks!

**Comment by chunweii** [comment]
For Websocket, some of the tests in e2e calls `Expect()` multiple times. If the usage checks are implemented, these tests will fail.

**Comment by gavv** [comment]
Oh, you're right. Websocket.Expect is intended to be called multiple times, once for each message. Seems it's also okay to call WithXxx methods between Expect calls.

So no modifications are needed in Websocket, this issue is relevant only for Request.
