### ISSUE TITLE
Sleep with context

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#163]
In `request.go`, when we retry request, we issue delay using `time.Sleep`.

It means that when we're sleeping, we ignore `context.Context`, if it's present. If context is cancelled, sleep wont be interrupted immediately, which is not desired.

If `r.config.Context` is not nil (it comes from Config or WithContext), we instead should listen for context cancellation and interrupt from sleep if needed (and fail retrying).

Note that we should listen on `r.config.Context`, not local `ctx` that we create in each retry iteration. The latter is for retry timeout.

Ideally this should be covered by both unit and e2e tests (see `e2e_context_test.go`).

**Comment by neverbeenthisweeb** [comment]
hi maybe some questions

we have `expErrorSuppressor` in https://github.com/gavv/httpexpect/blob/master/e2e_context_test.go#L94

and i've read some lines that use reporter in this code base

but I still cant connect the dots, my questions are:

- what is a reporter? what does it do? and why httpexpect has several reporter implementations
- why the expected error needs to be supressed in `e2e_context_test.go`?

thank you

**Comment by gavv** [comment]
Hi,

In short, the generic flow of httpexpect is:

* create Expect object using httpexpect.Default or httpexpect.WithConfig (root object)
* using Expect object, create Request object (request builder)
* use various Request methods to build http request (e.g. WithText, WithHeader)
* call Request.Expect(); it will send http request, receive http response, and create Response object based on received response
* use Response matcher object to perform assertions on response
* create child matcher objects to perform asserions on parts of response; e.g. Response.Headers() will return child matcher object to inspect headers; Response.Body() will return child matcher to inspect body

This is how failure reporting works in matcher objects:

* every matcher object (e.g. Response, Value, Array, Object, etc) have `chain`
* when a child matcher is created (e.g. you call Response.Body), the chain is cloned, and the clone is passed to the child object
* when matcher performs an assertion (e.g. Object.Equal), and assertion fails, it reports failure to its `chain`
* every `chain` object has:
  * fail bit; it is set after first failure; after it's set, all subsequent failures will be ignored in this chain and in future clones of this chain (i.e. in child matchers)
  * assertion handler; chain uses this handler to report failures

AssertionHandler may be redefined by user. However, in most cases, we use DefaultAssertionHandler, which does the following:

* formats failure using Formatter
* reports failure using Reporter

Again, Formatter can be redefined by user, but usually we just use DefaultFormatter.

> Note: User rarely needs to provide custom AssertionHandler. Providing Reporter is much easier. However in some complex cases, e.g. when user wants to integrate httpexpect with other testing frameworks, it may be helpful.

> Note: Defining custom formatter is rather complicated task and also is rarely needed.

Reporter is always provided by user. Reporter has very simple interface: it should provide one Errorf() method that will report already formatted message to testing suite.

Standard testing.T struct implements Reporter interface, and the user can just use `t` as reporter. In addition, we provide two nice Reporter implementations: AssertReporter and RequireReporter. They both use testify package (it's `assert` and `require` sub-packages`). When you will use them instead of bare testing.T, testify will add nice backtrace and indentation.

**Comment by gavv** [comment]
> why the expected error needs to be supressed in e2e_context_test.go?

expErrorSuppressor is a mock implementation of AssertionHandler. We use it in a few tests to catch situation when a failure is reported and this failure contains error with specific error message, e.g. "context canceled". It is needed to test that when context deadline expires, a correct failure is reported.

Note: e2e_context_test contains e2e, i.e. end-to-end tests (also called blackbox tests). Those tests intentionally don't know about internals of httpexpect, they use only their public interfaces. In particular, they can't modify or inspect chain. That's why they use a more complicated approach for catching failures with mocking of assertion handler.

**Comment by neverbeenthisweeb** [comment]
thank you for the explanation

that makes a lot of stuff clearer

gonna spent time to do some hands-on first

**Comment by gavv** [comment]
Merged!

**Comment by gavv** [comment]
I've added some comments to `chain` struct: c15c509fb05ef77a0d2aae0defc3e93e879618b0

**Comment by neverbeenthisweeb** [comment]
nice good comments
