### ISSUE TITLE
Improve test coverage of Request methods

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#164]
Add unit tests to improve coverage of request.go
No need to cover panics, but we should cover all assertions
https://coveralls.io/builds/54507988/source?filename=request.go

**Comment by labala-sravani** [comment]
@gavv , I have added few test cases for the above request.go file in the [PR 199](https://github.com/gavv/httpexpect/pull/199). Please review.

**Comment by gavv** [comment]
Thanks, will take a look tomorrow!

**Comment by gavv** [comment]
Merged!
