### ISSUE TITLE
Implement Array.Every and Object.Every

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#166]
Add new methods to Array and Object that allow to run function for every element:

```go
func (a *Array) Every(fn func(index int, value *httpexpect.Value)) *Array

...

array.Every(func(index int, value *httpexpect.Value) {
    // do something with value, for example:
    value.String().NotEmpty()
})
```

```go
func (o *Object) Every(fn func(key string, value *httpexpect.Value)) *Object

....

object.Every(func(key string, value *httpexpect.Value) {
    // do something with value, for example:
    value.String().NotEmpty()
})
```

New methods should have documentation comment with example and be covered by unit tests.

When array or object is constructing value to be passed to function, it should clone chain and append new path entry to it, like it is implemented in `Array.Iter()`, something like this:

```go
valueChain := a.chain.clone()
valueChain.enter("Every[%q]", key)

value := newValue(valueChain, o.value[key])
```

See also #168, #169.

**Comment by angshumanHalder** [comment]
Hey @gavv I would like to take up this issue if that's okay.

**Comment by gavv** [comment]
Sure, you're welcome! Thanks.

**Comment by gavv** [comment]
Merged.
