### ISSUE TITLE
 Implement Array.Filter and Object.Filter

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#169]
Add new methods to Array and Object that allow to filter element(s) by predicate:

```go
func (a *Array) Filter(fn func(index int, value *httpexpect.Value) bool) *Array

...

newArray := array.Filter(func(index int, value *httpexpect.Value) bool {
    // make assertions
    value.String().NotEmpty()

    // return boolean
    return true
})
```

```go
func (o *Object) Filter(fn func(key string, value *httpexpect.Value) bool) *Object

....

newObject := object.Filter(func(key string, value *httpexpect.Value) bool {
    // make assertions
    value.String().NotEmpty()

    // return boolean
    return true
})
```

New methods should have documentation comment with example and be covered by unit tests.

Description:

* Array.Filter returns new Array with only those elements from original array which match predicate
* Object.Filter is similar, but with map instead of array

Predicate is considered to succeed if BOTH conditions are met:

* assertions inside predicate did not fail (like `value.String().NotEmpty()` in the above example)
* predicate returned true

To implement this, we need to do something like this for every predicate call:

```go
predicateChain := a.chain.clone()
predicateChain.enter("Filter[%q]", key)

// make assertions inside predicate non-fatal
// they will be logged, but wont be reported as failures
predicateChain.setFatal(false)

// set failure callback that will be used by chain and will be inherited by its children
// this callback will just set a boolean, which indicates that the chain or one of its
// children had failed
predicateChainFailure := false
predicateChain.setFailCallback(func() {
    predicateChainFailure = true
})

value := newValue(predicateChain, ...)

ok := predicateFunc(key, value)

if !ok || predicateChainFailure {
    // predicate failed
} else {
    // predicate succeeded
}
```

See also #168, #166.

**Comment by vtech6** [comment]
Hi, I would like to help with this issue :)

**Comment by gavv** [comment]
@vtech6 Sure, you're welcome, thanks.

See this discussion: https://github.com/gavv/httpexpect/pull/176#discussion_r1033368911 Likely, the new chain.replace() method will be needed for Filter() as well.

Other discussions in #176 may be helpful too.

**Comment by vtech6** [comment]
@gavv I opened a [pull request](https://github.com/gavv/httpexpect/pull/178), let me know if I you have any suggestions.

**Comment by gavv** [comment]
Merged.
