### ISSUE TITLE
Implement DateTime getters

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#170]
Add new methods to DateTime struct:

* Zone - returns String with timezone name obtained from time.Time.Zone()
* Year - returns Number with time.Time.Year()
* Month - returns Number with time.Time.Month()
* Day - returns Number with time.Time.Day()
* WeekDay - returns Number with time.Time.Weekday()
* YearDay - returns Number with time.Time.YearDay()
* Hour - returns Number with time.Time.Hour()
* Minute - returns Number with time.Time.Minute()
* Second - returns Number with time.Time.Second()
* Nanosecond - returns Number with time.Time.Nanosecond()
* AsUTC - returns new DateTime with result of time.Time.UTC()
* AsLocal - returns new DateTime with result of time.Time.Local()

Each method should have documentation comment with example and be covered by unit tests.

**Comment by u5surf** [comment]
@gavv Hi, I'd like to work on this issue.

**Comment by gavv** [comment]
@u5surf Hi, you're welcome!

**Comment by gavv** [comment]
@u5surf Hi, do you still have plans on this?

**Comment by kaviranjan88** [comment]
@gavv Can I work on this?

**Comment by gavv** [comment]
@kaviranjan88 let's wait for rely from @u5surf, maybe some work is already started

**Comment by gavv** [comment]
@kaviranjan88 I guess you can pick this up if you're still interested.

**Comment by kaviranjan88** [comment]
@gavv Hi, I can pick this. Please assign to me.

**Comment by gavv** [comment]
Great!

**Comment by kaviranjan88** [comment]
@gavv Hi, I have created a pull request. https://github.com/gavv/httpexpect/pull/213

**Comment by gavv** [comment]
Landed
