### ISSUE TITLE
Implement Array.Transform and Object.Transform

### ISSUE THREAD

**Issue by angshumanHalder** [gavv/httpexpect#177]
Add new methods to Array and Object that allow to run function for every element:

```go
func (a *Array) Transform(fn func(index int, value *httpexpect.Value) (*httpexpect.Value, error)) *Array
...
array.Transform(func(index int, value *httpexpect.Value) (*httpexpect.Value, error) {
    // do something with value, for example:
    return httpexpect.NewValue(httpexpect.Reporter, value), nil
})
```

```go
func (a *Object) Transform(fn func(key string, value *httpexpect.Value) (*httpexpect.Value, nil)) *Object
...
object.Transform(func(key string, value *httpexpect.Value) *httpexpect.Value {
    // do something with value, for example:
    return httpexpect.NewValue(httpexpect.Reporter, value)
})
```
New methods should have documentation comment with example and be covered by unit tests.

When array or object is constructing value to be passed to function, it should clone chain and append new path entry to it.

```go
valueChain := a.chain.clone()
valueChain.replace("Transform[%q]", key)

value := newValue(valueChain, o.value[key])
```
Upon returning error or nil from the passed function Transform would use the original value in the new Array/Object

**Comment by angshumanHalder** [comment]
Hey @gavv can you assign this one to I just created it. I don't think I have the permission to assign it to myself. 😅

**Comment by gavv** [comment]
BTW I think there is no need to return error from callback function. If it wants to fail, it can use testing suite to do so (t.Fail, or testify).

**Comment by gavv** [comment]
I think, if callback returned nil, Transform should fail and return empty array/object. It should be so no matter if we return error or not.

And for error, since httpexpect is used in tests, and tests are already capable of reporting errors (using e.g. t.Errorf or testify assertions), then there is no need to introduce additional way to report them.

I mean, this:

```go
array.Transform(func(index int, value *httpexpect.Value) *httpexpect.Value) {
    if ... {
        t.Errorf("something happened")
        return nil
    }
    return <new value>
})
```

seems a bit more natural **in tests**, compared to this:

```go
array.Transform(func(index int, value *httpexpect.Value) (*httpexpect.Value, error)) {
    if ... {
        return nil, errors.New("something happened")
    }
    return <new value>, nil
})
```

What do you think?

**Comment by gavv** [comment]
BTW, instead of `httpexpect.NewValue()` and friends, user will most likely use `Expect.Value()` and friends, because it will return value with the same config. Note that the latter does not return error.

**Comment by angshumanHalder** [comment]
> I think, if callback returned nil, Transform should fail and return empty array/object. It should be so no matter if we return error or not.
> 
> And for error, since httpexpect is used in tests, and tests are already capable of reporting errors (using e.g. t.Errorf or testify assertions), then there is no need to introduce additional way to report them.
> 
> I mean, this:
> 
> ```go
> array.Transform(func(index int, value *httpexpect.Value) *httpexpect.Value) {
>     if ... {
>         t.Errorf("something happened")
>         return nil
>     }
>     return <new value>
> })
> ```
> 
> seems a bit more natural **in tests**, compared to this:
> 
> ```go
> array.Transform(func(index int, value *httpexpect.Value) (*httpexpect.Value, error)) {
>     if ... {
>         return nil, errors.New("something happened")
>     }
>     return <new value>, nil
> })
> ```
> 
> What do you think?

Makes sense. Let the function fail immediately upon returning nil leave it upto the user how to handle it.

**Comment by angshumanHalder** [comment]
> BTW, instead of `httpexpect.NewValue()` and friends, user will most likely use `Expect.Value()` and friends, because it will return value with the same config. Note that the latter does not return error.

Could you please explain what exactly you mean by `httpexpect.NewValue()` and friends?

**Comment by gavv** [comment]
> Could you please explain what exactly you mean by "httpexpect.NewValue() and friends"?

I mean, there are two ways to construct values:

* standalone functions: httpexpect.NewArray, httpexpect.NewObject, httpexpect.NewValue, etc (you used them in your examples); they return struct + error

* Expect methods: Expect.Array, Expect.Object, Expect.Value, etc. they don't return error; they are more convenient if you already have Expect instance because the returned values will use the same Config

**Comment by angshumanHalder** [comment]
> > Could you please explain what exactly you mean by "httpexpect.NewValue() and friends"?
> 
> I mean, there are two ways to construct values:
> 
> * standalone functions: httpexpect.NewArray, httpexpect.NewObject, httpexpect.NewValue, etc (you used them in your examples); they return struct + error
> * Expect methods: Expect.Array, Expect.Object, Expect.Value, etc. they don't return error; they are more convenient if you already have Expect instance because the returned values will use the same Config

Ahh okay. I got confused by the "friends" part. 😅

**Comment by angshumanHalder** [comment]
Hey @gavv 
```go
func (a *Array) Transform(fn func(index int, value *Value) *Value) *Array {
	a.chain.enter("Transform()")
	defer a.chain.leave()

	if a.chain.failed() {
		return a
	}

	if fn == nil {
		a.chain.fail(AssertionFailure{
			Type: AssertUsage,
			Errors: []error{
				errors.New("unexpected nil function argument"),
			},
		})
		return a
	}

	chainFailure := false

	array := []interface{}{}

	for index, val := range a.value {
		valueChain := a.chain.clone()
		valueChain.replace("Transform[%d]", index)

		valueChain.setFailCallback(func() {
			chainFailure = true
		})

		transformedValue := fn(index, newValue(valueChain, val))
		if transformedValue == nil {
			a.chain.fail(AssertionFailure{
				Type: AssertNil,
				Errors: []error{
					errors.New("unexpected nil return value"),
				},
			})
			return a
		}
		array = append(array, transformedValue)
	}

	if chainFailure {
		a.chain.setFailed()
	}

	return newArray(a.chain, array)
}
```

```go
	t.Run("Square Integers", func(ts *testing.T) {
		reporter := newMockReporter(ts)
		array := NewArray(reporter, []interface{}{2, 4, 6})
		newArray := array.Transform(func(_ int, val *Value) *Value {
			if v, ok := val.Raw().(float64); ok {
				return NewValue(ts, int(v)*int(v))
			}
			return nil
		})
		fmt.Println(newArray.value...)
		newArray.Contains([]interface{}{4, 16, 36})
		array.chain.assertOK(ts)
	})
```

Any idea why the return value of the above function is `{map[] map[] map[]}` ?

**Comment by gavv** [comment]
Merged!
