### ISSUE TITLE
Improve test coverage of Array and Object 

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#184]
See coverage reports here:

* https://coveralls.io/builds/54780436/source?filename=array.go
* https://coveralls.io/builds/54780436/source?filename=object.go

There are uncovered branches in Filter(), Every(), EqualUnordered(), NotEqualUnordered(), NotElements(), NotContainsOnly(). We should cover them in unit tests.

**Comment by taytzehao** [comment]
Please assign this to me, I am halfway there

**Comment by gavv** [comment]
Great, thanks!

**Comment by gavv** [comment]
@taytzehao hi, do you still have plans on this?

**Comment by gavv** [comment]
Unassigning, so that someone could pick it up.

**Comment by frankweate** [comment]
Hi gavv, could I possibly pick this up?

**Comment by gavv** [comment]
Sure, thanks!
