### ISSUE TITLE
Implement FatalReporter

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#187]
In reporter.go, we already have AssertReporter (uses testify/assert) and RequireReporter (uses testify/require), for non-fatal and fatal assertions, respectively.

If you don't use testify, you can directly use testing.T as reporter. httpexpect will call its Errorf method, so assertions will be non-fatal.

If you don't use testify, and want fatal assertions, you have to write your own reporter that invokes t.Fatalf. It would be nice to fill this gap and provide FatalReporter that does that for you - provides Errorf method that just invokes t.Fatalf.

Note: FatalReporter should use testing.TB interface, not testing.T struct.

Note: we should also update comments for Reporter interface and Config.Reporter field. Those comments list available reporter implementations.

**Comment by kairemor** [comment]
Can I check this?

**Comment by gavv** [comment]
You're welcome!
