### ISSUE TITLE
Implement Decode method

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#192]
Currently almost every struct has Raw() method, that returns the underlying value.

It would be nice to add to each such struct a complementary Decode() method, that will json-decode underlying value into the argument.

Example:

```go
var m map[string]interface{}

m = e.GET("/user").
	Expect().
	Status(http.StatusOK).
	JSON().
	Object().
	Raw()
```

Is same as:

```go
var m map[string]interface{}

e.GET("/user").
	Expect().
	Status(http.StatusOK).
	JSON().
	Object().
	Decode(&m)
```

This method becomes useful when you want to use specific type for decoding, e.g. struct:

```go
var user User

e.GET("/fruits/orange").
	Expect().
	Status(http.StatusOK).
	JSON().
	Object().
	Decode(&user)
```

BTW, this should give the same result:

```go
var user User

e.GET("/fruits/orange").
	Expect().
	Status(http.StatusOK).
	JSON().
	Decode(&user)
```

If argument is nil, the method should report failure (AssertUsage). If decoding fails, the method should also report failure (AssertValid).

The new method should be documented and covered with unit tests. Also it should be covered in e2e test (e2e_basic_test.go).

Also we should add example to README.

**Comment by Rohith-Raju** [comment]
@gavv I'd like to give this a shot

**Comment by Rohith-Raju** [comment]
Hey @gavv, I'll be getting back to this after 5th cause od my exams

**Comment by gavv** [comment]
Great, thanks, no hurry

**Comment by gavv** [comment]
Landed.
