### ISSUE TITLE
Add unit tests for reporters

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#196]
Add unit tests for reporters defined in reporter.go. To achieve this, we'll need a mock that implements assert.TestingT and require.TestingT.

**Comment by yimikao** [comment]
Hi @gavv can i pick this up

**Comment by gavv** [comment]
Sure, you're welcome!

**Comment by gavv** [comment]
@yimikao Hi, do you still have plans on this?

**Comment by yimikao** [comment]
@gavv sure, i was on break. I still plan to work on it.

**Comment by gavv** [comment]
Great, thanks. Just sorting out the issues.

**Comment by gavv** [comment]
Unassigning so that someone could pick this up.

**Comment by nhAnik** [comment]
Hi @gavv , can I work on this?

**Comment by gavv** [comment]
@nhAnik Sure, thanks!
