### ISSUE TITLE
Proposal: Use testing.TB instead of *testing.T

### ISSUE THREAD

**Issue by phifty** [gavv/httpexpect#20]
Currently, the constructor `httpexpect.New` takes an `*testing.T`. Using the interface `testing.TB` would make it possible to use the package in benchmarks too.

Cheers

**Comment by gavv** [comment]
Hi, thanks for reporting.

I've added `LoggerReporter` interface which is a subset of `testing.TB`. It's now used in `New`.

**Comment by phifty** [comment]
Great! Thanks for the fast response/fix. Seems to work.
