### ISSUE TITLE
Add more tests for Request

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#200]
Follow-up for #164 and #199

See https://coveralls.io/builds/55253043/source?filename=request.go

Some paths are uncovered:

* handling interpol errors
* handling errors from go-querystring/query
* handling multipart form errors
* `webocket request can not have body` error
* maybe some other uncovered branches

**Comment by kaviranjan88** [comment]
@gavv Hi, Can I try this one?

**Comment by gavv** [comment]
Sure, thanks!

**Comment by gavv** [comment]
@kaviranjan88 Hi, do you still have plans on this?

**Comment by kaviranjan88** [comment]
Hi Victor

Yes, I have written some test cases. Busy for couple of weeks..but will
create PR when I get some time.

Thanks,
Kavi

**Comment by gavv** [comment]
Great, thanks.

**Comment by gavv** [comment]
I'm going to close this issue and instead split it into a few more specific issues:

* https://github.com/gavv/httpexpect/issues/326
* https://github.com/gavv/httpexpect/issues/327
* https://github.com/gavv/httpexpect/issues/328

@kaviranjan88 feel free to ping me if you would like to submit patches for these or other issues. Thanks.
