### ISSUE TITLE
Add noCopy protection

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#203]
Add noCopy struct similar to https://github.com/valyala/fasthttp/blob/master/nocopy.go
Use it as the first field in all types that have chain field: Expect, Request, and all matcher structs (Value, Object, Array, etc.)

This is needed so that go vet will warn user if they try to copy instances of these structs.

**Comment by kairemor** [comment]
Can I go on this also ?

**Comment by gavv** [comment]
Sure, thank you
