### ISSUE TITLE
Implement additional constructors

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#204]
For each matcher type (Value, Object, Array, etc) that have constructor in form `NewFoo(reporter, value)`, implement an additional constructor in form `NewFooC(config, value)`.

New constructors should use newChainWithConfig() and config.withDefaults().

For example, for Array it would look like this:

```go
func NewArray(reporter Reporter, value []interface{}) *Array {
    return newArray(newChainWithDefaults("Array()", reporter), value)
}

func NewArrayC(config Config, value []interface{}) *Array {
    return newArray(newChainWithConfig("Array()", config.withDefaults()), value)
}

func newArray(parent *chain, val []interface{}) *Array {
   ...
```

New constructors should have documentation comment with code example and be covered by unit tests.

New constructors are NOT needed for Request and Websocket structs.

**Comment by Rohith-Raju** [comment]
@gavv can I give this a shot ?

**Comment by gavv** [comment]
Sure!
