### ISSUE TITLE
Add unit tests for chain cloning

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#206]
Add unit tests for constructors of all matcher structs (NewValue, NewArray, etc), verifying that each such constructor properly invokes `chain.clone()`.

It should be enough to check that:

* chain field of constructed object point to different address
* chain of constructed object has same path

**Comment by kairemor** [comment]
Hi @gavv Can I work on this ?

**Comment by gavv** [comment]
Sure, thank you
