### ISSUE TITLE
Add custom format template example

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#210]
Add a new example to `_examples` directory that uses [DefaultFormatter](https://pkg.go.dev/github.com/gavv/httpexpect/v2#DefaultFormatter) with custom FailureTemplate and TemplateFuncs fields.

I think it's a good idea to provide example of formatting assertions in JSON format, but other ideas are welcome too.

Add link to new example to README.

**Comment by edwinwijaya94** [comment]
Hi @gavv I would try to work on this

**Comment by gavv** [comment]
Thanks!
