### ISSUE TITLE
Add Request.WithReporter and WithAssertionHandler

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#234]
Add two new methods to Request:

* WithReporter(Reporter)
* WithAssertionHandler(AssertionHandler)

WithReporter(reporter) should be equivalent to:

```
WithAssertionHandler(DefaultAssertionHandler{
    Reporter: reporter,
    Formatter: r.config.Formatter,
})
```

WithAssertionHandler should update r.chain.handler with given handler. For that, we'll need to add new method chain.setHandler.

New methods should have documentation and tests. In tests, we should check that after these calls, request and it's newly created children (i.e. Response, its body, etc) start using new handler to report failures.

For that, we can create a mock reporter, pass it to request using WithReporter or WithAssertionHandler, then perform an assertion that will fail (req.Expect()....) and then check that the mock reporter is in failed state.

**Comment by kairemor** [comment]
I can go on this?

**Comment by gavv** [comment]
Sure!

**Comment by gavv** [comment]
@kairemor Hi, do you still have plans on this?

**Comment by gavv** [comment]
Unassigning, so that someone could pick this up. However feel free to ping me if you'll want to work on it.

**Comment by gavv** [comment]
Landed
