### ISSUE TITLE
Implement EventSource support

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#246]
_This issue depends on two other issues:_

* #244
* #245

**UPDATE**: both of them are completed now.

----

Add support for EventSource, a.k.a. Event Stream, a.k.a. SSE (Server-Sent Events).

It was requested a while ago here: https://github.com/gavv/httpexpect/discussions/145

We already have support for websockets, and support for SSE will have similar design, but simpler:

* `Request` will have new method `WithEventSource` (similar to Request.WithWebsocketUpgrade). It should just set `Accept` header field to `text/event-stream` (it should use withHeader method).

* `Response` will have new method `EventSource` (similar to Response.Websocket). It should check that response `Content-Type` header is `text/event-stream` and create a new instance of `EventSource` struct, attached to response body (it should use checkContentType method).

* `EventSource` method should also check if response body is bodyWrapper. If it is, it should call bodyWrapper.DisableRewinds, to prevent bodyWrapper from trying to save the whole (likely infinite) response in memory.

* `EventSource` struct (similar to Websocket struct) represents SSE connection. It should have methods: `Alias`, `WithReadTimeout` (set timeout for next read), `WithoutReadTimeout` (disable timeout for next read), `Expect` (read next message), `Disconnect` (close connection).

* `EventSource.Expect` should read next event from response body and return a new instance of `Event`.

* `Event` struct (similar to WebsocketMessage struct) represents a single event retrieved from server. It should have methods: `Raw`, `Alias`, `ID` (returns String), `Name` (returns String), `Data` (returns String).

----

Decoding of SSE events can be implemented using this package: https://github.com/alevinval/sse. It provides `Decoder` struct, which can read events from http.Response body.

New methods and structs should be covered with unit tests. In addition, we need a new e2e (end to end) test, similar to e2e_websocket_test.go. 

We also need a new example similar to `_examples/websocket.go`. To make sure that our SSE implementation is compatible with spec, it is suggested to use another package for SSE server in that example. A good candidate is https://github.com/r3labs/sse.

----

Wiki: https://en.wikipedia.org/wiki/Server-sent_events
Spec: https://html.spec.whatwg.org/multipage/server-sent-events.html

**Comment by g41797** [comment]
As far as I understand it's not urgent issue 
I just started my open source journey and pretty sure, that this feature will
take a lot of time for me
Pros: anyone depends on it
additional question - according to .gitignore, goland is used as ide
i am working with vscode

"Waiting for reply" :-)

**Comment by gavv** [comment]
You're welcome!

**Comment by g41797** [comment]
for further reading:
https://shopify.engineering/server-sent-events-data-streaming
https://meronhayle.me/implementing-sse-using-go/
https://thedevelopercafe.com/articles/server-sent-events-in-go-595ae2740c7a
https://bigboxcode.com/go-server-sent-events-sse
https://copyprogramming.com/howto/server-sent-events-golang
https://www.timeplus.com/post/websocket-vs-sse

**Comment by g41797** [comment]
go web servers for dummies:
https://www.dudley.codes/posts
https://www.alexedwards.net/blog/the-fat-service-pattern
https://threedots.tech/post/common-anti-patterns-in-go-web-applications/
https://medium.com/nerd-for-tech/golang-build-a-simple-web-server-and-interact-with-it-689ee0f4d1de
https://chidiwilliams.com/post/writing-cleaner-go-web-servers/
https://drstearns.github.io/tutorials/gomiddleware/
https://www.geeksforgeeks.org/how-to-build-a-simple-web-server-with-golang/
https://thecodeway.hashnode.dev/building-a-lightweight-web-server-with-golang
https://html.spec.whatwg.org/multipage/server-sent-events.html

---------------------------
https://www.openapis.org idl

**Comment by g41797** [comment]
interface **_EventTarget_** {
  [constructor](https://dom.spec.whatwg.org/#dom-eventtarget-eventtarget)();

  [undefined](https://webidl.spec.whatwg.org/#idl-undefined) [addEventListener](https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener)([DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) type, [EventListener](https://dom.spec.whatwg.org/#callbackdef-eventlistener)? callback, optional ([AddEventListenerOptions](https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions) or [boolean](https://webidl.spec.whatwg.org/#idl-boolean)) options = {});
  [undefined](https://webidl.spec.whatwg.org/#idl-undefined) [removeEventListener](https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener)([DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) type, [EventListener](https://dom.spec.whatwg.org/#callbackdef-eventlistener)? callback, optional ([EventListenerOptions](https://dom.spec.whatwg.org/#dictdef-eventlisteneroptions) or [boolean](https://webidl.spec.whatwg.org/#idl-boolean)) options = {});
  [boolean](https://webidl.spec.whatwg.org/#idl-boolean) [dispatchEvent](https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent)([Event](https://dom.spec.whatwg.org/#event) event);
};

callback interface EventListener {
  [undefined](https://webidl.spec.whatwg.org/#idl-undefined) handleEvent([Event](https://dom.spec.whatwg.org/#event) event);
};

dictionary EventListenerOptions {
  [boolean](https://webidl.spec.whatwg.org/#idl-boolean) capture = false;
};

dictionary AddEventListenerOptions : [EventListenerOptions](https://dom.spec.whatwg.org/#dictdef-eventlisteneroptions) {
  [boolean](https://webidl.spec.whatwg.org/#idl-boolean) passive;
  [boolean](https://webidl.spec.whatwg.org/#idl-boolean) once = false;
  [AbortSignal](https://dom.spec.whatwg.org/#abortsignal) signal;
};

interface **_EventSource_** : [EventTarget](https://dom.spec.whatwg.org/#interface-eventtarget) {
  [constructor](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource)(USVString url, optional [EventSourceInit](https://html.spec.whatwg.org/multipage/server-sent-events.html#eventsourceinit) eventSourceInitDict = {});

  readonly attribute USVString [url](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-url);
  readonly attribute boolean [withCredentials](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-withcredentials);

  // ready state
  const unsigned short [CONNECTING](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-connecting) = 0;
  const unsigned short [OPEN](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-open) = 1;
  const unsigned short [CLOSED](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-closed) = 2;
  readonly attribute unsigned short [readyState](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-readystate);

  // networking
  attribute [EventHandler](https://html.spec.whatwg.org/multipage/webappapis.html#eventhandler) [onopen](https://html.spec.whatwg.org/multipage/server-sent-events.html#handler-eventsource-onopen);
  attribute [EventHandler](https://html.spec.whatwg.org/multipage/webappapis.html#eventhandler) [onmessage](https://html.spec.whatwg.org/multipage/server-sent-events.html#handler-eventsource-onmessage);
  attribute [EventHandler](https://html.spec.whatwg.org/multipage/webappapis.html#eventhandler) [onerror](https://html.spec.whatwg.org/multipage/server-sent-events.html#handler-eventsource-onerror);
  undefined [close](https://html.spec.whatwg.org/multipage/server-sent-events.html#dom-eventsource-close)();
};

dictionary EventSourceInit {
  boolean withCredentials = false;
};

**SSEClient** struct represents SSE connection:

It should have methods: 
- Alias ???
- WithReadTimeout
- WithoutReadTimeout
- Expect (read next event)
- Disconnect (close connection).

SSEClient uses EventSource (internally or as parameter?)

EventSource should be **_interface_** - specific implementation depends on used SSE/HHTP package. This approach allows to use different client/server SSE/HTTP implementations

Response will have new method SSEClient etc....

LastID 
- added automatically by EventSource impl
- parameter of test for simulation of diff. flows?

**Comment by g41797** [comment]
From github.com/r3labs/sse/v2

type Event struct {
	timestamp time.Time
	ID        []byte
	Data      []byte
	Event     []byte
	Retry     []byte
	Comment   []byte
}


From HTTP5 :
Event handler | Event 
-- | --
onopen    | "open"
onmessage | "message"
onerror   | "error"

Check events supported by sse

**Comment by g41797** [comment]
Regarding wsUpgrade bool (see WithWebsocketUpgrade)

Should be replaced with something like:

type clientType int

const (
	typeRegular     clientType = iota // HTTP client
	typeWebSocket                     // WebSocket
	typeEventSource                   // EventSource (Server Sent Event)
)

**Comment by g41797** [comment]
What about shortcut:
 
Request will have new method EventSource (similar to Response.Websocket). It should check TBD , create a new instance of EventSource struct.

EventSource struct (similar to Websocket struct) represents SSE connection. It should have methods: Alias, WithReadTimeout (set timeout for next read), WithoutReadTimeout (disable timeout for next read), Expect (read next message), Disconnect (close connection), ??? Connect() ???

EventSource.Expect should read next event from TBD and return a new instance of Event.

Event struct (similar to WebsocketMessage struct) represents a single event retrieved from server. It should have methods: Raw, Alias, ID (returns String), Name (returns String), Data (returns String).

Looks closer to client side flow

I have no problem to implement former design, but before implementation it worth to discuss alternatives
Waiting for reply

**Comment by g41797** [comment]
Request will have new method WithEventSource. It should just set Accept header field to text/event-stream (it should use withHeader method).
Better move this knowledge to EventSource
- EventSource will have function Transformers for adding required for SSE headers 
- Request.WithEventSource will get all transformers and apply them 

Headers:
"Cache-Control", "no-cache"
"Accept", "text/event-stream"
"Connection", "keep-alive"

Response will have new method EventSource (similar to Response.Websocket). It should check that response Content-Type header is text/event-stream and create a new instance of EventSource struct, attached to response body (it should use checkContentType method).

**Comment by g41797** [comment]
Decoding of SSE events can be implemented using this package: https://github.com/alevinval/sse. It provides Decoder struct, which can read events from http.Response body.

Installation of alevinval/sse - failed
Open new issue #https://github.com/alevinval/sse/issues/61

Meantime 3 sources from sse were copied to local repo for further development

**Comment by g41797** [comment]
looks this feature has low priority

**Comment by morigs** [comment]
Actually it'd be very cool to support SSE. I have a few SSE endpoints I'd like to cover with tests using httpexpect
