### ISSUE TITLE
Add standalone OAuth example

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#251]
Add a small example to `_examples` directory (say, `oauth.go` and `oauth_test.go`) that runs small OAuth server with hardcoded credentials and tests it using httpexpect.

Server can use https://github.com/go-oauth2/oauth2
Client can use https://pkg.go.dev/golang.org/x/oauth2
Example can be based on https://github.com/go-oauth2/oauth2/tree/master/example

To use httpexpect with OAuth, you'll need to create a client using oauth2.NewClient and pass it to Config.

Also we need to add link to new example to README: https://github.com/gavv/httpexpect#examples

**Comment by fahimbagar** [comment]
Hi @gavv, I've added the PR: https://github.com/gavv/httpexpect/pull/267

I'm not quite sure if the example is as expected.

**Comment by gavv** [comment]
@fahimbagar Thanks! Will review in upcoming days.

**Comment by fahimbagar** [comment]
take your time @gavv

**Comment by gavv** [comment]
Landed!
