### ISSUE TITLE
Create reentrancy test for chain

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#255]
We need to be sure that `chain` does not invoke AssertionHandler under chain's lock. It's forbidden because AssertionHandler may be provided by user, and if user code will indirectly access the chain again, and the chain is locked, it would cause deadlock.

This already works as needed, but we need to cover this behavior with a unit test for chain.

The test will:

* set custom AssertionHandler which Success and Failure methods invoke chain.enter

* invoke chain methods to make it reporting success and failure 

* check that AssertionHandler methods were actually called

Here we simulate accessing chain from user code. If chain calls user code under its lock, this test will hang.

We already have a similar test for Environment: TestEnvironment_Reentrancy. It checks that AssertionHandler may access Environment and it wont cause deadlock.

**Comment by regularcoder** [comment]
I'm interested in taking a shot at this.

**Comment by gavv** [comment]
You're welcome!

**Comment by gavv** [comment]
Landed
