### ISSUE TITLE
Honor FloatFormat when formatting maps and slices

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#258]
In `DefaultFormatter.formatValue`, when we format a float, we do it accordingly to `DefaultFormatter.FloatFormat` field. It selects whether to format floats in scientific or decimal notation.

However, when we format a value which is a map or slice with some floats inside (for example slice of floats or map of slices of floats), we ignore `FloatFormat` field.

This is related to two calls in `formatValue`:

* `json.MarshalIndent` (formatting of json values)
* `sq.Sdump` (formatting of go values)

We should teach `formatValue` to honor `FloatFormat` setting in these two calls too. For example, if `FloatFormatScientific` is used, a slice of floats should use scientific notation when formatting all floats.

This should be covered with tests.

**Comment by edwinwijaya94** [comment]
Hi @gavv I would like to work on this

**Comment by gavv** [comment]
You're welcome, thanks!

**Comment by gavv** [comment]
Closing, opened a new task for alternative algorithm: #430.

See here: https://github.com/gavv/httpexpect/pull/399#issuecomment-1751719566
