### ISSUE TITLE
Add Environment.Clear

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#260]
Add new method Environment.Clear which removes all values.

New method should have documentation comment with code example and be covered by tests.

**Comment by e-berman** [comment]
I'll give this one a go @gavv.

Sorry for the stupid question, but you want to keep the keys and only clear the values, correct?

**Comment by gavv** [comment]
Cool, thank you. Nooe, sorry for misunderstanding, I meant just to remove everything, keys and values. To allow the user to reset state.
