### ISSUE TITLE
Add unit test TestFormatter_FailureContext

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#262]
Add unit test that checks how DefaultFormatter builds FormatData from AssertionContext and how formatting options affect this.

The test should fill AssertionContext fields (TestName, RequestName, Path, AliasedPath), set formatting options in DefaultFormatter, and invoke DefaultFormatter.buildFormatData, similar to TestFormatter_Failure* tests.

In retrieved FormatData struct it should check fields that correspond to AssertionContext fields.

It should check the following formatting options:

* DisableNames
* DisablePaths
* DisableAliases

Related: https://github.com/gavv/httpexpect/issues/165

**Comment by frankweate** [comment]
Hi gavv! Could I have a go at this?

**Comment by frankweate** [comment]
@gavv I was half way through working on this issue, I'll stop working on this? I'm happy to find other issues to work on!

**Comment by aliziyacevik** [comment]
hi @gavv, can I give it a go ?

**Comment by gavv** [comment]
Landed.

@frankweate Sorry for late reply and for inconvenience. I have just merged #418. Thanks anyway!

@aliziyacevik Thanks, I have merged existing PR.
