### ISSUE TITLE
Add unit test TestFormatter_FailureErrors

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#264]
This test should check how DefaultFormatter handles Errors field of the failure. It's similar to other TestFormatter_Failure* tests.

It should check the following cases:

* nil Errors slice
* non-nil empty Errors slice
* Errors slice with nil error
* Errors slice with typed nil error
* Errors slice with one error
* Errors slice with multiple errors

For each case, we should call buildFormatData and check FormatData.Errors.

Related: https://github.com/gavv/httpexpect/issues/165, https://github.com/gavv/httpexpect/issues/262

**Comment by Darrellbor** [comment]
@gavv i'd like to help out with this issue

**Comment by gavv** [comment]
You're welcome!
