### ISSUE TITLE
Add unit test for error propagation

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#265]
Add a test to expect_test.go, which checks the following.

After an object's operation (e.g. Array.IsEqual) fails, we expect that:

* [x] subsequent operations on that object will be no-op, i.e. they won't report failures
* [x] newly created child objects (e.g. Array.Length) will have failed chain and won't report failures
* [x] previously created nested object won't be affected, i.e. they will report failures
* [x] newly created child objects of objects' parent won't be affected, i.e. they will report failures
* [x] previously created child objects of objects' parent won't be affected, i.e. they will report failures

This behavior is described [in docs](https://pkg.go.dev/github.com/gavv/httpexpect/v2#hdr-Failure_handling).

This test will be partially similar to TestExpect_Branches, however it should set different reporters to different objects to check if this or that action causes failure reporting or not.

**Comment by neverbeenthisweeb** [comment]
hi @gavv can I work on this?

**Comment by gavv** [comment]
Sure, thanks!

**Comment by neverbeenthisweeb** [comment]
@gavv question

what does the syntax `flags&(flagFailed|flagFailedChildren)` do here? (or...what is this syntax called by? i'm clueless to figure out the keyword to google :umbrella: )

```go
if flags&(flagFailed|flagFailedChildren) == 0 {
    handler.Success(&context)
}
```
https://github.com/gavv/httpexpect/blob/master/chain.go#L387

thanks

**Comment by gavv** [comment]
Yes, it's bitwise AND. Unlike logical and (&&), it allows working with separate buts in a single integer value instead of treating the whole value as true or false. 

Individual buts are used here to represent different flags. The first bit is for one flag, second for another, and so on. If the corresponding bit is 1, the flag is considered to be set; if the bit is 0, the flag is unset.

It's a common idiom for representing flags. It's especially useful when you have many flags, so instead of many boolean fileds you need only one integer field. Less memory and less clutter in code.

**Comment by gavv** [comment]
Random article from google: https://blog.podkalicki.com/bit-level-operations-bit-flags-and-bit-masks/#:~:text=This%20is%20done%20by%20using,%E2%80%9C0%E2%80%9D%20(zero).

**Comment by gavv** [comment]
The particular snippet you mentioned checks that both of the specified flags are unset, i.e. both of the corresponding  bits are zero.

**Comment by neverbeenthisweeb** [comment]
ok thanks for the answer and references

_today i learned_

**Comment by neverbeenthisweeb** [comment]
@gavv To make sure my understanding of child-parent relationship, I've created a draft in https://github.com/gavv/httpexpect/pull/369

Would you please take a look? Thanks

Btw, I still don't get the difference between child-parent relationship and the _previously created nested object_ part mentioned in the point below

> previously created nested object won't be affected, i.e. they will report failures

Would you mind to provide an example of _previously created nested object_ case? Thanks

**Comment by gavv** [comment]
The draft looks fine!

> previously created nested object won't be affected, i.e. they will report failures

Here by "nested" I also meant "child".

Let's take a look at the points in the issue and your tests:

* `subsequent operations on that object will be no-op, i.e. they won't report failures` - it's your "subsequent operations"

* `newly created child objects (e.g. Array.Length) will have failed chain and won't report failures` - it's your "newly created child objects"

* `previously created nested object won't be affected, i.e. they will report failures` - **it should be like your "newly created child objects", but the child object (arr.Value) should be created before failure, not after failure**

* `newly created child objects of objects' parent won't be affected, i.e. they will report failures` - it's your "newly created child objects of object's parent"

* `previously created child objects of objects' parent won't be affected, i.e. they will report failures` - it's your "previously created child objects of object's parent"

**Comment by neverbeenthisweeb** [comment]
Ok got it. Thanks for the explanation.

**Comment by gavv** [comment]
Landed
