### ISSUE TITLE
Migrate examples to echo-jwt

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#268]
Currently echo.go example uses `middleware.JWT` from `github.com/labstack/echo/v4/middleware`: https://github.com/gavv/httpexpect/blob/66b55a3d0ccac9f8d270a5ec609079de54b8777c/_examples/echo.go#L43

It is deprecated and should be replaced with `echojwt.JWT` from `github.com/labstack/echo-jwt`.

**Comment by fahimbagar** [comment]
Hi @gavv, adding PR for this: https://github.com/gavv/httpexpect/pull/281

**Comment by gavv** [comment]
Thanks!
