### ISSUE TITLE
Move e2e tests to separate package

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#272]
We have a set of end-to-end tests in files named `e2e_xxx_test.go`. These tests are intended to be blackbox, i.e. they should use only public API of httpexpect and should not access private fields.

In this issue we want to move all such tests into a separate subdirectory `e2e`, and accordingly separate package (but same module).

Some e2e tests violate blackbox rule and access private fields. These tests should be fixed. For example, if a test accesses chain field to invoke assertNotFailed or assertFailed, the test can be reworked to use mock reporter. Instead of checking chain field directly, it can provide custom reporter and then check if a failure was reported or not.

After completing the task, we should also do the following:

* [x] add e2e tests to Makefile targets
* [x] add e2e tests to CI (building, linting, running)
* [x] on CI, merge test coverage from unit and e2e test; useful links: [[1]](https://stackoverflow.com/questions/63842225/go-test-coverage-over-different-packages), [[2]](https://github.com/wadey/gocovmerge)

**Comment by regularcoder** [comment]
I'm interested in signing up for this.

**Comment by gavv** [comment]
Great, thanks!

**Comment by regularcoder** [comment]
Hello, yes I do, apologies for the delay. I will try to get it done this weekend - by 2nd April.

**Comment by gavv** [comment]
@regularcoder thanks, no worries, just checking if it's abandoned,  which happens often. Take your time :)

**Comment by gavv** [comment]
Follow-up commits:

* 7c851155bb17c148cb24266cb96264dac7a0957b - add e2e to makefile targets
* 1965b0891c6159e8cb84e6101bd1720635be79cb - add e2e to CI steps

**Comment by gavv** [comment]
One more:

* fc338613061e29bb244318e39b7df391f5686928 - add e2e to coverage reports

**Comment by gavv** [comment]
Final commit: 907b2e90d49485f6605a5fe824901cc0c92830af

**Comment by gavv** [comment]
Seems now everything is done. @regularcoder Thanks!
