### ISSUE TITLE
Add test TestE2EReport_LineWidth

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#273]
Add a new test that checks work of DefaultFormatter.LineWidth option.

The test should produce a failure with long lines (i.e. long assertion path and long error) and see how it's formatted with several variants of LineWidth:

* zero value (means use default limit): all lines should be shorter than default limit
* small positive value: all lines should be shorter than configured limit
* very large positive value: there are some long lines
* negative value (means no limit): there are some long lines

This test should not be very strict to the report format. Ideally it should check only width of lines in produced report and occurrence of assertion path and error message in that report.

Related: #165

**Comment by dhanusaputra** [comment]
hi, can i do this task? thank you

**Comment by gavv** [comment]
Sure, you're welcome!
