### ISSUE TITLE
Refactor some unit tests

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#284]
Some of our tests declare multiple variables and then do various checks on each variable, like this:

```go
value1 := NewMatch(reporter, []string{"m"}, nil)
value2 := NewMatch(reporter, []string{}, nil)

value1.IsEmpty()
value1.chain.assertFailed(t)
value1.chain.clearFailed()

value2.IsEmpty()
value2.chain.assertNotFailed(t)
value2.chain.clearFailed()
```

This approach is error-prone: it's easy to make a check on wrong variable and often it can remain unnoticed.

----

This tests need to be refactored in one of the following ways:

1. In simple tests, instead of declaring multiple vars, we can reuse a single one, like this:

    ```go
    var value *Match

    value = NewMatch(reporter, []string{"m"}, nil)
    value.IsEmpty()
    value.chain.assertFailed(t)
    value.chain.clearFailed()

    value = NewMatch(reporter, []string{}, nil)
    value.IsEmpty()
    value.chain.assertNotFailed(t)
    value.chain.clearFailed()
    ```

2. In more complicated tests, we can split the test into subtests, and isolate local vars there.

3. We can also convert tests to table-driven style.

----

Feel free to choose one of the approaches for each test based on your own judgement.

Tests to be refactored:

* [x] TestMatch_Empty
* [x] TestMatch_ValuesEmpty
* [x] TestNumber_EqualNaN
* [x] TestArray_IsEqual/types (split into subtests)
* [x] TestString_Empty
* [x] TestString_IsAscii
* [x] TestString_NotAscii
* [x] TestString_AsNumber
* [x] TestString_AsDateTime
* [x] TestValue_GetObject
* [x] TestValue_GetArray
* [x] TestValue_GetNumber
* [x] TestValue_GetBoolean
* [x] TestValue_IsObject
* [x] TestValue_IsArray
* [x] TestValue_IsString
* [x] TestValue_IsNumber
* [x] TestValue_IsBoolean
* [x] TestWebsocketMessage_CodeAndType
* [x] TestWebsocketMessage_NoContent

----

Pull requests that address only part of this issue are welcome too!

Related: https://github.com/gavv/httpexpect/issues/283

**Comment by CarbonGabe** [comment]
Hi @gavv. Can I work on this issue?

**Comment by gavv** [comment]
@gpjservais Sure, thanks! I'd suggest splitting work into a few PRs.

**Comment by gavv** [comment]
Would be nice if we can merge TestNumber_EqualNaN into TestNumber_IsEqual.

**Comment by gpjservais** [comment]
@gavv I agree. I'll plan to merge them with my next PR.

**Comment by gavv** [comment]
All PRs are merged
