### ISSUE TITLE
Add more canonization tests for Array

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#288]
Most httpexpect methods perform convert value to its canonical form before comparison. See docs: https://pkg.go.dev/github.com/gavv/httpexpect/v2#hdr-Value_equality

In array_test.go, tests for many Array methods have "canonization" subtest, which checks that corresponding methods performs that conversion. For example: TestArray_IsEqual/canonization, TestArray_ConsistsOf/canonization, and others.

We need to add similar "canonization" subtests to tests that are missing it:

* [x] TestArray_IsEqualUnordered
* [x] TestArray_InList
* [x] TestArray_ContainsAny
* [x] TestArray_ContainsOnly
* [ ] ~TestArray_Filter~ TestArray_Transform (produced array should be in canonical form)

Pull requests that address only part of this issue are welcome too!

Related: #283

**Comment by Darrellbor** [comment]
Hey @gavv i'm new to open source and find this project interesting and would like to contribute by starting with this
i'm currently going through the codebase as well as the `HACKING.MD` file. if there's anything else i should be aware of, i'd appreciate

**Comment by Darrellbor** [comment]
yes

**Comment by Darrellbor** [comment]
@gavv I have pushed a PR that addresses `TestArray_IsEqualUnordered` please review and let me know if I'm on the right track so i can take corrections before pushing the rest

**Comment by gavv** [comment]
@Darrellbor I've created a separate issue for Transform tests: https://github.com/gavv/httpexpect/issues/297 and described in more details what do we need to do. Please leave a comment there in case you would like to work on it.

**Comment by gavv** [comment]
Closing this one, thank you.
