### ISSUE TITLE
Add canonization tests for Array.Transform and Object.Transform

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#297]
Follow-up issue for https://github.com/gavv/httpexpect/issues/288

Array.Transform applies a function for each array element and returns a new, transformed array, with the results of the function. As many other functions in this library, Transform performs canonization of the values. For example, if the function returned `myInt(123)`, corresponding element will be converted to its canonical form, i.e. `float64(123.0)`.

The same is true for Object.Transform.

We should add "canonization" subtests to TestArray_Transform and TestObject_Transform, which check that: if transformation function returns value in non-canonical form, the corresponding element in array or object returned from Transform will have canonical form.

**Comment by Darrellbor** [comment]
I would like to pick up on this task @gavv
