### ISSUE TITLE
Convert a few DateTime and Duration tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#310]
Convert the following tests to table-driven style:

* TestDateTime_InRange
* TestDateTime_InList
* TestDuration_InRange
* TestDuration_InList

TestNumber_InDelta is an example of desired style.

**Comment by PiotrLewandowski323** [comment]
Hi,
I'd like to work on this issue.

**Comment by gavv** [comment]
Thanks!
