### ISSUE TITLE
Add more multipart form tests

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#328]
TestRequest_BodyMultipart covers usage of WithMultipart + WithForm/WithFormField/WithFile/etc.

coveralls [reports](https://coveralls.io/builds/57516032/source?filename=request.go) that there are several uncovered branches in various methods, related to multipart form handling.

You can find all such places by searching for `if r.multipart` and checking for red blocks nearby.

We should add subtests to TestRequest_BodyMultipart to cover all such branches.

**Comment by neverbeenthisweeb** [comment]
hi @gavv , can I work on this?

**Comment by neverbeenthisweeb** [comment]
btw, I am thinking to have a mocked `Request.multipart` to simulate errors for some cases (such as [request.go#L1672](https://coveralls.io/builds/57516032/source?filename=request.go#L1672) in the red blocks)

so, the mocked `Request.multipart` will be something like

```go
type mockMultipartImpl struct{}

func (mm *mockMultipartImpl) WriteField(fieldname, value string) error {
    return errors.New("error from mock")
}
```

however, this requires us to update `Request.multipart` from `struct` into `interface` so that in can be mocked

and provide a custom setter for `Request.multipart`

```go
// Existing
func (r *Request) WithMultipart() *Request {

// New
type multipartWriterInterface interface {}

func (r *Request) withCustomMultipart(m multipartWriterInterface) *Request {
```

wdyt about this solution? is it a bit..._overkill_?

**Comment by neverbeenthisweeb** [comment]
> btw, I am thinking to have a mocked Request.multipart to simulate errors for some cases (such as for .WriteField in [request.go#L1672](https://coveralls.io/builds/57516032/source?filename=request.go#L1672) in the red blocks)

@gavv I've created a draft to demonstrate the point above (https://github.com/gavv/httpexpect/issues/328#issuecomment-1479206229)

please check https://github.com/gavv/httpexpect/pull/344

thank you

LMK if you have concern or anything

PS. sry if the structure is a bit messy, but it should convey my point

**Comment by gavv** [comment]
IIRC we used similar approach with `Request.sleepFn`

**Comment by neverbeenthisweeb** [comment]
> Request.WithMultipart calls multipart.NewWriter and passes r.formbuf to it, which implements io.Writer. It should be enough for us to intercept this call and pass our own io.Writer that will return error when needed.

I see, thanks for the insight.

**Comment by neverbeenthisweeb** [comment]
@gavv I've updated the PR based on the suggestion above 

https://github.com/gavv/httpexpect/pull/344

Please check, thanks!

**Comment by neverbeenthisweeb** [comment]
@gavv hi, it is ready for full review
