### ISSUE TITLE
Convert String tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#330]
Convert each subtest of the following tests to table-driven style:

* TestString_IsEqual
* TestString_IsEqualFold
* TestString_InList
* TestString_InListFold
* TestString_Contains
* TestString_ContainsFold
* TestString_HasPrefix
* TestString_HasSuffix
* TestString_HasPrefixFold
* TestString_HasSuffixFold

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

Related issues: #309, #324

**Comment by neverbeenthisweeb** [comment]
@gavv 
Hi, I can work on this.
Btw for `TestString_IsEqual` (and other tests), should we separate the test for `IsEqual` and `IsNotEqual`?
From:
```
func TestString_IsEqual(t *testing.T) {
	reporter := newMockReporter(t)

	value := NewString(reporter, "foo")

	assert.Equal(t, "foo", value.Raw())

	value.IsEqual("foo")
	value.chain.assertNotFailed(t)
	value.chain.clearFailed()

	value.IsEqual("FOO")
	value.chain.assertFailed(t)
	value.chain.clearFailed()

	value.NotEqual("FOO")
	value.chain.assertNotFailed(t)
	value.chain.clearFailed()

	value.NotEqual("foo")
	value.chain.assertFailed(t)
	value.chain.clearFailed()
}
```
To (something like):
```
func TestString_IsEqual(t *testing.T) {

}

func TestString_IsNotEqual(t *testing.T) {

}
```
https://github.com/gavv/httpexpect/blob/master/string_test.go#L215
Wdyt?

**Comment by gavv** [comment]
Thanks! 

I recently refactored all tests to cover IxXxx and NotXxx in the same test, because the set of checks is very similar.

It works especially well with table driven approach, take a look for Number tests.

**Comment by neverbeenthisweeb** [comment]
@gavv 
Ok, btw what does the term `canonization` means here? And why it is separated from `basic`?
I found a bit of clue here:
> Why:
> 
> in basic, some checks should fail, and some succeed
> in canonization, it's ok to include only successful checks
> in invalid argument, all checks should fail

https://github.com/gavv/httpexpect/issues/309#issuecomment-1446827043

But still have no answer

**Comment by gavv** [comment]
See description of this issue 

https://github.com/gavv/httpexpect/issues/288

It also has a lonk to documentation

**Comment by gavv** [comment]
"canonization" is a common features of many httpexpect methods

Correspondingly, each test has a subtest for this feature

**Comment by neverbeenthisweeb** [comment]
@gavv 
```
func (s *String) IsEqual(value string) *String {
```
Considering that the `string.go` methods (e.g. `InList`, `IsEqual`, etc) accept `string` instead of `interface{}`, does it mean we **don't need** the canonization tests for this issue? CMIIW

**Comment by gavv** [comment]
Oh, yes, you're right
