### ISSUE TITLE
Colorize json values

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#334]
Follow-up for #161.

Currently `defaultFailureTemplate` colorizes expected/actual/reference as follows:

```
{{ .Actual | indent | color .EnableColors "HiMagenta" }}
```

The following improvement is suggested:

* add new function "colorjson" to defaultTemplateFuncs
* if colors are disabled, the function will return original value
* the function will try to parse value as json
* if value is not json, the function just returns original value
* if value is json, the function colorizes it using https://github.com/TylerBrock/colorjson
* it uses custom color schema; I suggest: HiMagenta for string; Cyan for number, bool, null; default for key (not too much different colors, readable on dark and light background, and aligns with current colors schema)

For "delta", let's always use Cyan, like we use Cyan for all numbers in the color schema suggested above.

Related: #335, #343.

**Comment by fbirn** [comment]
Hello, i would like to look into this and try to implement it!

**Comment by gavv** [comment]
@fbirn Hi! Do you still have plans on this?

**Comment by dminkovski** [comment]
@gavv Hello, I would love to take a shot at this if you do not mind :)

**Comment by gavv** [comment]
@dminkovski Thanks!

**Comment by gavv** [comment]
Landed
