### ISSUE TITLE
Convert Array tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#351]
Convert each subtest of the following tests to table-driven style:

* [ ] TestArray_ConsistsOf
* [ ] TestArray_Contains
* [ ] TestArray_ContainsAll
* [ ] TestArray_ContainsAny
* [ ] TestArray_ContainsOnly
* [ ] TestArray_HasValue

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

**Comment by frankweate** [comment]
Hey gavv! I'd be happy to do this if you want?

**Comment by gavv** [comment]
Thanks!
