### ISSUE TITLE
Convert Object tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#352]
Convert each subtest of the following tests to table-driven style:

* TestObject_ContainsKey
* TestObject_ContainsValue
* TestObject_ContainsSubset
* TestObject_HasValue

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

**Comment by Darrellbor** [comment]
@gavv i'd like to help out with this

**Comment by gavv** [comment]
You're welcome!
