### ISSUE TITLE
Convert DateTime tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#354]
Convert each test to table-driven style:

* TestDateTime_IsEqual
* TestDateTime_IsGreater
* TestDateTime_IsLesser

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

**Comment by frankweate** [comment]
Hey gavv! I'd be happy to do this if you want?

**Comment by gavv** [comment]
Welcome, thanks!
