### ISSUE TITLE
Convert WebsocketMessage tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#356]
Convert each test to table-driven style:

* TestWebsocketMessage_CloseMessage
* TestWebsocketMessage_TextMessage
* TestWebsocketMessage_BinaryMessage
* TestWebsocketMessage_MatchTypes
* TestWebsocketMessage_MatchCodes

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

**Comment by aliziyacevik** [comment]
Hello there, may I handle this one ?

**Comment by gavv** [comment]
You're welcome, thanks!

**Comment by gavv** [comment]
Landed
