### ISSUE TITLE
Refactor Websocket tests

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#357]
After introducing new chain.assert() method, we can simplify many websocket tests.

In `websocket_test.go`, find all table-driven tests that have `assertOk` field and refactor them as follows:

* replace `assertOk bool` with `result chainResult`
* instead of `assertOk: true`, use `result: success`
* instead of `assertOk: false`, use `result: failure`
* instead of:

    ```go
	if tc.assertOk {
		ws.chain.assert(t, success)
	} else {
		ws.chain.assert(t, failure)
	}
    ```

    use:

    ```go
	ws.chain.assert(t, tc.result)
    ```

**Comment by antara-gandhi** [comment]
@gavv i'd like to claim this issue!

**Comment by gavv** [comment]
@antara-gandhi welcome :)
