### ISSUE TITLE
Refactor Environment tests

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#358]
After introducing new chain.assert() method, we can simplify many websocket tests.

In `environment_test.go`, find all table-driven tests that have `ok` field and refactor them as follows:

* replace `ok bool` with `result chainResult`
* instead of `ok: true`, use `result: success`
* instead of `ok: false`, use `result: failure`
* instead of:

    ```go
	if tc.ok {
		ws.chain.assert(t, success)
	} else {
		ws.chain.assert(t, failure)
	}
    ```

    use:

    ```go
	ws.chain.assert(t, tc.result)
    ```

**Comment by edwinwijaya94** [comment]
Hi @gavv can I work on this?

**Comment by gavv** [comment]
Sure, thanks!
