### ISSUE TITLE
Refactor json path and json schema tests

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#359]
Tests for many matcher structs (e.g. Array, Object), have a test called TestXxx_Getters (e.g. TestArray_Getters, TestObject_Getters), which contain checks for struct's `Path` and `Schema` methods.

We need to find all these checks and extract them into separate tests TestXxx_Path and TestXxx_Schema. Please place new tests before TestXxx_Getters.

Besides extraction, we need to refactor the checks themselves. Instead of performing a series of checks on the same value and clearing the chain every time, we should perform a check on a new instance. This way checks will be more isolated (they won't use shared state) and clean (we won't mutate chain internal state from tests).

For example, consider this set of checks:

```go
value.Schema(`{"type": "object"}`)
value.chain.assert(t, success)
value.chain.clear()

value.Schema(`{"type": "array"}`)
value.chain.assert(t, failure)
value.chain.clear()
```

It can be refactored in one of the following ways:

1. We can re-recreate value for each check and re-assing var:

    ```go
	var value *Object

	value = Object(...)
	value.Schema(`{"type": "object"}`)
	value.chain.assert(t, success)

	value = Object(...)
	value.Schema(`{"type": "array"}`)
	value.chain.assert(t, failure)
    ```

2. Alternatively, we can split the test into subtests and create a variable inside each of them.

3. Alternatively, we can write the test in table-driver style.

Feel free to choose one of the approaches for each test based on your own judgement.

**Comment by antara-gandhi** [comment]
can i claim this? @gavv

**Comment by gavv** [comment]
Sure, thanks!
