### ISSUE TITLE
Convert canon tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#360]
Convert each of the following tests to table-driven style:

* TestCanon_Number
* TestCanon_Array
* TestCanon_Map
* TestCannon_Decode

**Comment by VikranthBala** [comment]
@gavv Can I work on this?

**Comment by gavv** [comment]
Sure, thanks!

**Comment by VikranthBala** [comment]
Hey, I think I am done with tests, can I know, if there is an naming convention to be followed, for the file and the testCases, as we already have existing tests. How Should I move forward with it?

**Comment by gavv** [comment]
I assumed that we just change canon_test.go, and I guess test names are not changed, they just are split into subtests (using table).

You can take a look at TestCannon_Decode for an example of naming subtests.

**Comment by VikranthBala** [comment]
Hey @gavv  , I have raised a PR, can you have a look at it, and let me know, if that is how I should be doing it, or should I change it. PR: #370

**Comment by VikranthBala** [comment]
I have raised a new PR, as I had some issues with the previous PR. The new PR is at #395. Do let me know if I have to make any changes, Thanks. If I made any mistakes, do let me know. Thanks @gavv

**Comment by gavv** [comment]
Thanks. BTW, you can always just force-push to PR's branch, I think there is no real need to create a new PR.
