### ISSUE TITLE
Update iris example to 12.2.0

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#374]
Iris example is here:

* https://github.com/gavv/httpexpect/blob/master/_examples/iris.go
* https://github.com/gavv/httpexpect/blob/master/_examples/iris_test.go

Currently it uses iris 12.1.8. Recently iris 12.2.0 was released, we should bump dependency version and port code to new version.

Automatic update had failed: https://github.com/gavv/httpexpect/pull/373

**Comment by cmg2146** [comment]
Hi @gavv, I can take this one.
