### ISSUE TITLE
Convert TestRequest_Conflicts to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#383]
Convert each subtest of TestRequest_Conflicts to table-driven style.

Use TestRequest_Usage and TestRequest_Order as a reference (but they have only one table, and TestRequest_Conflicts should have multiple tables, one per subtest).

**Comment by Darrellbor** [comment]
is this task taken? @gavv @diPhantxm

**Comment by diPhantxm** [comment]
> is this task taken? @gavv @diPhantxm

Hi. Yeah, I thought it wouldn't take so much time, so I decided not to assign to the task

**Comment by gavv** [comment]
@Darrellbor Yep, there is a PR already.

@diPhantxm Thanks, merged!

**Comment by gavv** [comment]
@diPhantxm Ideally, please leave a comment in an issue when you're working on a task. Apparently someone also also didn't find your PR and made a duplicate one: https://github.com/gavv/httpexpect/pull/404
