### ISSUE TITLE
Convert Object tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#386]
Convert each subtest of the following tests to table-driven style:

* TestObject_IsEmpty
* TestObject_IsEqual
* TestObject_InList

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

**Comment by jeremyphua** [comment]
Hello! I would like to work on this.

**Comment by gavv** [comment]
Welcome, thanks!
