### ISSUE TITLE
Convert Array tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#387]
Convert each subtest of the following tests to table-driven style:

* [x] TestArray_IsEmpty
* [x] TestArray_IsEqual
* [x] TestArray_IsEqualUnordered
* [x] TestArray_InList

`TestNumber_IsEqual/basic` can be used as a reference for table-driven style.

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

**Comment by aliziyacevik** [comment]
hi @gavv , PR is ready for this issue. I can open it if you could assign me. Thanks.

**Comment by gavv** [comment]
Great!
