### ISSUE TITLE
Check for extra arguments in WebsocketMessage constructor

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#392]
newWebsocketMessage should report failure if `len(closeCode) > 1`, similar to how newResponse handles `len(opts.rtt) > 1`.

New test should be added - TestWebsocketMessage_CloseCode, which checks:

* if closeCode is not passed to ctor, message Code() is zero
* if closeCode is passed, message Code is the same
* if multiple closeCodes are passes, ctor reports failure

**Comment by aliziyacevik** [comment]
hi @gavv, PR is ready for this one.

**Comment by gavv** [comment]
BTW I don't see any PR

**Comment by aliziyacevik** [comment]
I just pushed it. @gavv

**Comment by gavv** [comment]
> Hi @gavv , can you see it now ?

Yep, thanks!
