### ISSUE TITLE
Add macOS and Windows to github actions

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#413]
Currently our CI runs checks only on Linux.

We need to add macOS and Windows to the matrix of "build" and "examples" jobs, and fix possible issues.

**Comment by AnandaIlyasa** [comment]
hi @gavv i want to try this one, assign me please

**Comment by gavv** [comment]
@AnandaIlyasa Welcome, thanks!

**Comment by reapedjuggler** [comment]
Hi, @gavv Is this in progress or shall I take it up? Thank you 🚀

**Comment by neda1985** [comment]
@gavv does somebody already work on this issue or i can pick it ?

**Comment by gavv** [comment]
Fixed in #426
