### ISSUE TITLE
gorilla/websocket dependency no longer maintained

### ISSUE THREAD

**Issue by joelmbell** [gavv/httpexpect#421]
The [Gorilla Toolkit](https://github.com/gorilla) has been moved to maintenance mode. Can we move to an alternative in a future version?

**Comment by g41797** [comment]
[fasthttp/websocket](https://github.com/fasthttp/websocket) contains forked version of [gorilla/websocket](https://github.com/gorilla/websocket)
I'd like to stress the fact - it wasn't changed and still based on net/http
see https://github.com/fasthttp/websocket/issues/36
At least it's the place to open issues in case of failure
For short term looks as solution

**Comment by g41797** [comment]
[fasthttp/websocket](https://github.com/fasthttp/websocket/issues/36#issuecomment-1572499478) works
so in the future version gorilla/websocket may be replaced with fasthttp/websocket

**Comment by aliziyacevik** [comment]
I can take this guys. maybe we can use this library https://pkg.go.dev/nhooyr.io/websocket.

**Comment by aliziyacevik** [comment]
of course in case of fasthttp/websocket doesn't work since it contains a fork of gorilla.

**Comment by gavv** [comment]
Hi,

Gorilla is now unarchived and has new maintainers, so I think we can continue using it.
