### ISSUE TITLE
WithHandler()

### ISSUE THREAD

**Issue by ybbus** [gavv/httpexpect#43]
Hi.

Would be great for convenience if there is somehwere a call like WithHandler() or UsingHandler() so you just can provide a handler function to test.

Or is there some way to do this with some of the NewXXX() calls?

So you do not have to go through the whole &Client{ Transport: ... stuff every time if you are testing a lot of handlers.

**Comment by gavv** [comment]
Hi, added this to the latest master.

Example: https://github.com/gavv/httpexpect#per-request-client-or-handler

Documentation:
https://godoc.org/github.com/gavv/httpexpect#Request.WithClient
https://godoc.org/github.com/gavv/httpexpect#Request.WithHandler

**Comment by ybbus** [comment]
Great! Thanks.
