### ISSUE TITLE
Expectation Builder also for responses

### ISSUE THREAD

**Issue by ybbus** [gavv/httpexpect#44]
Hi.

At the moment using httpexpect I do the following when my test are quite similar:

beforeEach() {
  defaultExpectation := test.Get("/somePath").Header("AlwaysSet", "true")
}

So all tests are using this as base and they differ in some stuff like body or return expectations.

But I also have many tests where the response is is often equal in some parts.

E.g. the response should always have a header set.

So I would like to have a way to prebuild an expectation that also includes some common expectations for the response without yet executing the expectation.

Maybe something like this:

beforeEach() {
  defaultExpectation := test.Get("/somePath").Header("AlwaysSet", "true").WithResponse().Header("ABC").Equals("DEF")
}

and I can use it in my tests like this:

defaultExpectation.Body(requestBody).Expect().Status(200)
and it would also set the path, the request header and would check for the response header.

An idea would be to not execute the test when calling Expect() but with an exclusive call like Eval() or Run()...

**Comment by ybbus** [comment]
What I also noticed:
Without setting the method, you are not able to set anything else.

So if a want to prebuild an expectation, where the method differs, but for example the auth header should always be set, I cannot do this.

Maybe you could get inspired by my http mock server I just build some days ago (so it is pretty pretty alpha).
https://github.com/ybbus/httpmockserver/blob/master/request_expectation.go#L14

the expectation is created by mockServer.EXPECT()
and the everything can follow, not only the method functions.

**Comment by ybbus** [comment]
Hi.
Sorry my bad. This seems to work fine using the Builder()

Greetings,
Alex

**Comment by ybbus** [comment]
Nope doesn't. Since EXPECT() triggers the request you cannot predefine response expectations without triggering the request.

**Comment by ybbus** [comment]
I think now I get it:

You can either prebuild a expectation using a method like PUT(), GET() etc... But then without EXPECT() since this would trigger the request directly.
Like:
``` golang
func beforeEach() {
    preparedExpectation = expectClient.PUT("...").WithJSON("...") // no EXPECT() call here
}

// and then execute it:
preparedExpectation.EXPECT().Status(...).JSON()
```

Or you can use the Builder() even with expect, but then you cannot prebuild the method GET / POST etc since the builder is directly exectued on this method.
Like:

``` golang
func beforeEach() {
	preparedExpectation = testClient.Builder(func(request *httpexpect.Request) {
		request.WithHeader("...", "...")
		request.Expect().Status(200)
	})
}

// and then execute it:
preparedExpectation.PUT("...")
```

So you cannot have both:
Preparing a Method and also preparing some result expectations?

**Comment by gavv** [comment]
I've added support for reusable response matchers:

* https://godoc.org/github.com/gavv/httpexpect#Expect.Matcher
* https://godoc.org/github.com/gavv/httpexpect#Request.WithMatcher

See example in README: https://github.com/gavv/httpexpect#reusable-matchers
