### ISSUE TITLE
Please use semver tagging

### ISSUE THREAD

**Issue by ybbus** [gavv/httpexpect#47]
See: http://semver.org/

Helps a lot when using go package management tools like https://github.com/golang/dep

Thanks

**Comment by gavv** [comment]
Hi, sorry for delay.

httpexpect currently uses `v<NUMBER>` branches for stable versions that provide backward compatibility (actually there is only one version currently, v1).

Could you clarify what is the problem with go dep? Does it require minor and patch versions to be present? Or does it require tags instead of branches?

**Comment by ybbus** [comment]
Hi.
Yes, go dep needs major minor and patch as described by semver.org.
Many go-libraries already use this convention. This makes it easy to do somce kind of versioning / version selection in dependency management tools like go dep.

The rules a quite simple:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

So your v1 should at least be: v1.0.0 for tools to correctly process the version of the project.

**Comment by smthpickboy** [comment]
Russ Cox's new vgo proposal also adopts semver. Would be really good for httpexpect to use it.

**Comment by ybbus** [comment]
Hi.
This discussion is open for half a year and it is just about tagging a release in a golang / semver compatible way. vgo is now available for evaluation and also uses semver for dependency management...

**Comment by ybbus** [comment]
no plans to provide a semver compatible tag?
go mod is out and also using it

**Comment by gavv** [comment]
Hi, sorry for delay. I finally have some time for this project again.

Thanks for your explanation. I've added the v1.0.0 tag and added a note to the README:

> When the master is merged into a stable branch, a new version tag is assigned to the branch head. The versions are selected according to the semantic versioning scheme.

Closing this fow now, feel free to reopen if I missed something.
