### ISSUE TITLE
Cookie validation should support MaxAge too

### ISSUE THREAD

**Issue by michael2008** [gavv/httpexpect#52]
Currently, the `httpexpect` checks cookie expiration time like this:

```
// Expires returns a new DateTime object that may be used to inspect
// cookie expiration date.
//
// Example:
//  cookie := NewCookie(t, &http.Cookie{...})
//  cookie.Expires().InRange(time.Now(), time.Now().Add(time.Hour * 24))
func (c *Cookie) Expires() *DateTime {
	if c.chain.failed() {
		return &DateTime{c.chain, time.Unix(0, 0)}
	}
	return &DateTime{c.chain, c.value.Expires}
}
```
which is not compatible with rfc standards.

`Expires` in the cookie is obsolete and should be replaced with `MaxAge`. Only IE 8 and below still identifies only `Expires`, while most browsers can interpret both `Expires` and `MaxAge`.

So I am wondering if the `func (c *Cookie) Expires()` can checks both `Expires` and `MaxAge`. Or should there be another function like  `func (c *Cookie) MaxAge()`  to deal with `MaxAge` property.

**Comment by gavv** [comment]
I've added [Cookie.MaxAge](https://godoc.org/github.com/gavv/httpexpect#Cookie.MaxAge) method along with the new [Duration](https://godoc.org/github.com/gavv/httpexpect#Duration) type to the master branch.

I didn't touch the old Expires() method to keep backwards compatibility.
