### ISSUE TITLE
Object o1.Equal(Object o2) behavior is surprising

### ISSUE THREAD

**Issue by lpar** [gavv/httpexpect#53]
o1 := httpexpect.NewObject(t, map[string]interface{}{"foo": 123})
	o2 := httpexpect.NewObject(t, map[string]interface{}{"foo": 123})
	o1.Equal(o2)

Based on the documentation for Object.Equal, I would have expected this test to pass, but it doesn't. You need to do `o1.Equal(o2.Raw())` instead.

**Comment by gavv** [comment]
Thanks for reporting. I've updated comments for this and other similar methods.
