### ISSUE TITLE
Response time?

### ISSUE THREAD

**Issue by sofixa** [gavv/httpexpect#6]
Hi there, great project! 
I checked out your doc and examples and i didn't see anything, but maybe i've missed it - is there a way to get the response time for a request?

Cheers,
Adrian

**Comment by gavv** [comment]
Currently, no. I can add it (I hope tomorrow) or you could send a PR.

I think we need:

```go
func (r *Response) Time() *Number { ... }
```

and we can also print response time to log.

**Comment by gavv** [comment]
Done, see [`Response.Time()`](https://godoc.org/github.com/gavv/httpexpect#Response.Time).

Example usage:

```go
e.GET(...).Expect().Time().Equal(10 * time.Millisecond)
```

Example log output using `DebugPrinter`:

```
        printer.go:55: GET /fruits/apple HTTP/1.1
                Host: 127.0.0.1:46032
                User-Agent: Go-http-client/1.1
                Accept-Encoding: gzip
                
        printer.go:72: HTTP/1.1 200 OK 105.217µs
                Content-Length: 39
                Content-Type: application/json
                Date: Sun, 19 Jun 2016 11:32:50 GMT
                
                {"colors":["green","red"],"weight":200}
```

Time is measured using [`gavv/monotime`](https://github.com/gavv/monotime).

**Comment by sofixa** [comment]
Wow, that was fast. Thanks a lot, i'll give it a try these days!

**Comment by gavv** [comment]
I've renamed `Response.Time` to [`Response.Duration`](https://godoc.org/github.com/gavv/httpexpect#Response.Duration) to avoid confusion with response date/time support which I'm currently implementing.

Closing this, feel free to reopen if you encounter any problems.
