### ISSUE TITLE
Should WithHost be added?

### ISSUE THREAD

**Issue by sidot3291** [gavv/httpexpect#66]
We're building tests for requests that perform differently based on the Host.

We were able to get the behavior we want with httpexpect via:
`WithHeader("Host", "example.com")`

I wanted to raise that maybe a `WithHost` option should be added.

I believe this would be more consistent with Go's Request struct, which (if I understand correctly) chooses the Host header based on either (1) the Host field, (2) the Host header, or (3) URL.Host.
```
    // For client requests, Host optionally overrides the Host
    // header to send. If empty, the Request.Write method uses
    // the value of URL.Host. Host may contain an international
    // domain name.
    Host string
```
https://godoc.org/net/http#Request

**Comment by gavv** [comment]
Hi!

Agree, sounds reasonable. One thing to think about is whether we should somehow handle the case when both WithHost and WithHeader("Host") are provided. Probably not.

I don't have much time for this right now. You can either submit a PR or let the issue hang for a while until I add it later.

**Comment by flaviostutz** [comment]
I think the latest call should override previous. For example:
```golang
WithHeader("Host": "server1")
WithHost("server2")
```
'server2' should prevail

```golang
WithHost("server2")
WithHeader("Host": "server5")
```
'server5' should prevail

**Comment by pedromss** [comment]
Hello. I was thinking about picking this up if I understood the goal. We want to be able to do:

```go
req.WithHost("somehost.com")
```
And have it set the `Host` header on the request.

Is that correct?

**Comment by gavv** [comment]
Merged!
