### ISSUE TITLE
Support adding middleware to finalize HTTP requests

### ISSUE THREAD

**Issue by mrosales** [gavv/httpexpect#68]
This request might seem a little strange, so I'll outline the use case first. I have an API that requires the requests to sign the body, and I'd like to use `httpexpect` to create one of these signed requests.

In order to do this, I need to construct a signature from the request body, http headers, full path, query string, HTTP protocol. See the [AWS Request Signing docs](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html) for an example of a similar scheme.

I'm not suggesting something too specific to my use case, but rather suggesting to implement something like a "request finalizer" or "request middleware" that lets you perform a function to modify the outgoing HTTP request object. I currently have to viable workarounds.

1. Prepend a logger, since is called basically when I want:

```go

func TestSignedRequest(t *testing.T) {
	// ...

	e := httpexpect.WithConfig(httpexpect.Config{
		BaseURL: baseURL,
		Client: &http.Client{
			Jar:     httpexpect.NewJar(),
			Timeout: time.Second * 30,
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
			requestFinalizerFunc(func(r *http.Request) {
				// copy request body
				// compute signature headers
				// set header
			}),
			httpexpect.NewCompactPrinter(t),
		},
	})

	// e.POST(...)
}


type requestFinalizerFunc func(r *http.Request)

// Request implements httpexpect.Printer.Request.
func (finalizer requestFinalizerFunc) Request(req *http.Request) {
	if req != nil {
		finalizer(req)
	}
}
```

2. Override the `http.Client`, so we can transform the outgoing request.

I opted for the logger approach since it allows the request to be transformed after it is constructed but before being logged or sent. Would you consider adding a hook that exposes something like the following:

```
e.POST("/foo/bar").
    WithBytes(someBytes).
    WithRequestTransformer(func(r *http.Request){
        // modify the request here
    })
```

It could be used with something like:

```
e := httpexpect.New(t, "http://example.com")

signed := e.Builder(func (req *httpexpect.Request) {
	req.WithRequestTransformer(func(r *http.Request) {
		// sign my request
	})
})

signed.POST("/foo/bar").WithBytes([]byte("some bytes to sign"))
```

**Comment by gavv** [comment]
Hi, sorry for late reply.

Yes, `WithRequestTransformer` idea looks good! I'll assign `help wanted` tag so that someone could implement it.

**Comment by unbeatable01** [comment]
I'd like to work on this, could you assign it to me?

**Comment by gavv** [comment]
Done!

@shreyubee We already had a PR, I've merged it.

**Comment by gavv** [comment]
https://github.com/gavv/httpexpect#request-transformers
