### ISSUE TITLE
License not present in the imported fasthttp-contrib/websocket package

### ISSUE THREAD

**Issue by BharathB23** [gavv/httpexpect#74]
Hello,

github.com/fasthttp-contrib/websocket package imported in this project doesn't contain a license and implicitly makes this project to come under default copyright laws which means, that the project retain all rights to the source code and no one can reproduce, distribute, or create derivative works.

Though github.com/fasthttp-contrib/websocket is forked copy of github.com/gorilla/websocket, which has a proper license, I think we need github.com/fasthttp-contrib/websocket too to have a proper license, since it's being directly imported by this project.
    
Can we solve this issue by dropping github.com/fasthttp-contrib/websocket package or in anyother possible way.

Have also created an issue against github.com/fasthttp-contrib/websocket, but the project doesn't seem to be active for a year or more.

Thank you.

**Comment by kataras** [comment]
I have no access to the repository itself as I left from the organisation but I grant all rights to use the library to @gavv as I am the one and only contributor of that library.

**Comment by gavv** [comment]
Likely, we can just switch to https://github.com/fasthttp/websocket. I'll look at it in upcoming days.

**Comment by gavv** [comment]
Done. Push to master, v2, and tagged a new release v2.1.0. Also, the minimum supported Go version was bumped to Go 1.14.

**Comment by BharathB23** [comment]
Gavv, Thank you for your time and efforts spent to resolve the observation reported.
