### ISSUE TITLE
307 and 308 redirects are not followed

### ISSUE THREAD

**Issue by colinclerk** [gavv/httpexpect#76]
307 and 308 redirects rely on a http.Request.GetBody function for http.Client to follow the redirect.

Golang typically sets GetBody by default in http.NewRequest:
https://github.com/golang/go/blob/2cd2ff6f564dce5be0c4fb7f06338ff7af3fc9a9/src/net/http/request.go#L872-L914

But httpexpect has a cool progressive request builder, so at the time NewRequest is called, body is actually nil (the third argument here):
https://github.com/gavv/httpexpect/blob/c3000bc283cd364de398ca4e3f8d91f4a7591114/request.go#L99

To resolve, I believe httpexpect can set GetBody in the call to Expect() where the request is finalized (using the same logic as GoLang above):
https://github.com/gavv/httpexpect/blob/c3000bc283cd364de398ca4e3f8d91f4a7591114/request.go#L865

**Comment by gavv** [comment]
Thanks for reporting! I'll take a look at upcoming days.

**Comment by gavv** [comment]
Thanks again for report and sory for delay. I've added WithRedirectPolicy() and WithMaxRedirects() methods, which define how to handle redirects.

For compatibility, default policy is FollowRedirectsWithoutBody, which matches earlier behavior. However, now you can use FollowAllRedirects to allow 307 and 308 redirects. With this policy, httpexpect will automatically set GetBody.

You can also use DontFollowRedirects if you want to inspect redirect response without following it.

These methods work only if you use http.Client. They wont work with custom implementation of httpexpect.Client interface.

Commit: ec89b2b9a268ebba1bd56f11c4fae9776ed1d56d

Example: https://github.com/gavv/httpexpect#redirection-support
