### ISSUE TITLE
Add unit tests for redirect and retry support

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#91]
Redirect methods (WithRedirectPolicy, WithMaxRedirects) and retry methods (WithRetryPolicy, WithMaxRetries, WithRetryDelay) are already covered with end-to-end tests (e2e_redirect_test.go, e2e_retry_test.go), but unit tests are missing.

It would be nice to add unit tests for these methods to request_test.go. In unit tests, we can use `http.Client` with custom `Transport` set to our own implementation of `http.RoundTripper` interface. There we can check what requests are generated by httpexpect and produce fake responses to trigger redirects and retries.

**Comment by gopalanvinay** [comment]
@gavv could I make a PR to add these tests?

**Comment by gavv** [comment]
@gopalanvinay Sure, you're welcome.

**Comment by gopalanvinay** [comment]
@gavv could I be added as a collaborator? Permission to push to the repo is currently denied to my account :)

**Comment by gavv** [comment]
@123vivekr Hi! Yes, there is unmerged PR with unresolved issues, see #94. Feel free to pick up the task.

**Comment by 123vivekr** [comment]
I'm a beginner in Golang. I'll give this a try and submit a PR for review soon.

**Comment by kaustubhmallik** [comment]
Hi @gavv is it still open? If so, I would like to pick it up. :)

**Comment by 123vivekr** [comment]
@kaustubhmallik Feel free to take it up.

**Comment by gavv** [comment]
Hi, the issue is still open. See also discussion in #94.

**Comment by neverbeenthisweeb** [comment]
@gavv hi, for testing the `WithRetryDelay` wdyt if we do `time.Sleep` in the unit test? then assert if the sleep time is as expected

or you might have concerns about this?

my concern is that by doing sleep, the unit test will be slower by some miliseconds (approximately, because we sleep)

**Comment by gavv** [comment]
I think short sleeps, maybe below 10-20 ms per test, are OK.

**Comment by neverbeenthisweeb** [comment]
got it, will keep the sleep around that

**Comment by gavv** [comment]
Landed
