### ISSUE TITLE
Add WithContext and WithTimeout

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#92]
Currently, httpexpect never sets request context before sending it.

It would be nice to add context.Context field to Config. Request.encodeRequest should pass this context to the constructed http.Request.

It may be also useful to have per-request contexts. Thus, we should also add Request.WithContext. If called, the given context should be used instead of the one from Config.

Finally, we should provide a convenient method for simply setting request timeout - WithTimeout. If the user calls it, we should wrap context with context.WithDeadline().

We should ensure that:

* cancelling global or per-request context cancels retry loop (Request.retryRequest);
* expiring per-request timeout cancels only a single request in the retry loop (so likely WithDeadline call should be in retryRequest).

We need end-to-end integration tests (like, e.g., e2e_redirect_test.go) for global context, per-request context, and per-request timeout. Tests should check that if the server blocks, cancelling context or expiring timeout will unblock client.

Ideally, we also need unit tests that check that we correctly construct http.Request (i.e. it has proper context).

New methods should be documented. Also, a usage example should be added to README.

**Comment by gtourkas** [comment]
#97

**Comment by gavv** [comment]
Merged!
